// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Alike Angular";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/alikeangular/v27/3qTrojWunjGQtEBlIcwMbSoI7kQwbQ.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/alikeangular/v27/3qTrojWunjGQtEBlIcwMbSoI7kowbS7F.woff2",
  },
  "math": {
    "400-normal": "https://fonts.gstatic.com/s/alikeangular/v27/3qTrojWunjGQtEBlIcwMbSoI7jgwbS7F.woff2",
  },
  "symbols": {
    "400-normal": "https://fonts.gstatic.com/s/alikeangular/v27/3qTrojWunjGQtEBlIcwMbSoI7iowbS7F.woff2",
  },
} as const;

export type AlikeAngularWeight = "400";
export type AlikeAngularStyle = "normal";
export type AlikeAngularSubset = "latin" | "latin-ext" | "math" | "symbols";
export type AlikeAngularOptions = GoogleFontOptions<AlikeAngularWeight, AlikeAngularStyle, AlikeAngularSubset>;

/**
 * Alike Angular — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class AlikeAngular extends GoogleFont<AlikeAngularWeight, AlikeAngularStyle, AlikeAngularSubset> {
  constructor(options?: AlikeAngularOptions) {
    super(FAMILY, FACES, options);
  }
}
