// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Allison";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/allison/v13/X7nl4b88AP2nkbvZCCGa4Q.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/allison/v13/X7nl4b88AP2nkbvZCC-a4fTg.woff2",
  },
  "vietnamese": {
    "400-normal": "https://fonts.gstatic.com/s/allison/v13/X7nl4b88AP2nkbvZCC6a4fTg.woff2",
  },
} as const;

export type AllisonWeight = "400";
export type AllisonStyle = "normal";
export type AllisonSubset = "latin" | "latin-ext" | "vietnamese";
export type AllisonOptions = GoogleFontOptions<AllisonWeight, AllisonStyle, AllisonSubset>;

/**
 * Allison — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Allison extends GoogleFont<AllisonWeight, AllisonStyle, AllisonSubset> {
  constructor(options?: AllisonOptions) {
    super(FAMILY, FACES, options);
  }
}
