// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Andada Pro";

const FACES = {
  "latin": {
    "400-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaSpEM.woff2",
    "400-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIlqSA.woff2",
    "500-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaSpEM.woff2",
    "500-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIlqSA.woff2",
    "600-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaSpEM.woff2",
    "600-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIlqSA.woff2",
    "700-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaSpEM.woff2",
    "700-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIlqSA.woff2",
    "800-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaSpEM.woff2",
    "800-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIlqSA.woff2",
  },
  "latin-ext": {
    "400-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaRJEMx_E.woff2",
    "400-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIdqSIkI.woff2",
    "500-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaRJEMx_E.woff2",
    "500-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIdqSIkI.woff2",
    "600-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaRJEMx_E.woff2",
    "600-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIdqSIkI.woff2",
    "700-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaRJEMx_E.woff2",
    "700-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIdqSIkI.woff2",
    "800-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaRJEMx_E.woff2",
    "800-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIdqSIkI.woff2",
  },
  "vietnamese": {
    "400-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaRZEMx_E.woff2",
    "400-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIZqSIkI.woff2",
    "500-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaRZEMx_E.woff2",
    "500-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIZqSIkI.woff2",
    "600-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaRZEMx_E.woff2",
    "600-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIZqSIkI.woff2",
    "700-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaRZEMx_E.woff2",
    "700-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIZqSIkI.woff2",
    "800-italic": "https://fonts.gstatic.com/s/andadapro/v24/HhyTU5Qi9-SuOEhPe4LtAIxaRZEMx_E.woff2",
    "800-normal": "https://fonts.gstatic.com/s/andadapro/v24/HhyRU5Qi9-SuOEhPe4LtAIZqSIkI.woff2",
  },
} as const;

export type AndadaProWeight = "400" | "500" | "600" | "700" | "800";
export type AndadaProStyle = "italic" | "normal";
export type AndadaProSubset = "latin" | "latin-ext" | "vietnamese";
export type AndadaProOptions = GoogleFontOptions<AndadaProWeight, AndadaProStyle, AndadaProSubset>;

/**
 * Andada Pro — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class AndadaPro extends GoogleFont<AndadaProWeight, AndadaProStyle, AndadaProSubset> {
  constructor(options?: AndadaProOptions) {
    super(FAMILY, FACES, options);
  }
}
