// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Angkor";

const FACES = {
  khmer: {
    "400-normal": "https://fonts.gstatic.com/s/angkor/v35/H4cmBXyAlsPdnlbO_iY_0Lo.woff2",
  },
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/angkor/v35/H4cmBXyAlsPdnlbO9SY_.woff2",
  },
} as const;

export type AngkorWeight = "400";
export type AngkorStyle = "normal";
export type AngkorSubset = "khmer" | "latin";
export type AngkorOptions = GoogleFontOptions<AngkorWeight, AngkorStyle, AngkorSubset>;

/**
 * Angkor — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Angkor extends GoogleFont<AngkorWeight, AngkorStyle, AngkorSubset> {
  constructor(options?: AngkorOptions) {
    super(FAMILY, FACES, options);
  }
}
