// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Averia Gruesa Libre";

const FACES = {
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/averiagruesalibre/v22/NGSov4nEGEktOaDRKsY-1dhh8eEtIx3ZYm6Dwg.woff2",
  },
  "latin-ext": {
    "400-normal":
      "https://fonts.gstatic.com/s/averiagruesalibre/v22/NGSov4nEGEktOaDRKsY-1dhh8eEtIx3ZYmCDwnSL.woff2",
  },
} as const;

export type AveriaGruesaLibreWeight = "400";
export type AveriaGruesaLibreStyle = "normal";
export type AveriaGruesaLibreSubset = "latin" | "latin-ext";
export type AveriaGruesaLibreOptions = GoogleFontOptions<
  AveriaGruesaLibreWeight,
  AveriaGruesaLibreStyle,
  AveriaGruesaLibreSubset
>;

/**
 * Averia Gruesa Libre — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class AveriaGruesaLibre extends GoogleFont<
  AveriaGruesaLibreWeight,
  AveriaGruesaLibreStyle,
  AveriaGruesaLibreSubset
> {
  constructor(options?: AveriaGruesaLibreOptions) {
    super(FAMILY, FACES, options);
  }
}
