// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "B612";

const FACES = {
  latin: {
    "400-italic": "https://fonts.gstatic.com/s/b612/v13/3Jn8SDDxiSz36juCGxCk.woff2",
    "400-normal": "https://fonts.gstatic.com/s/b612/v13/3JnySDDxiSz36j6yGQ.woff2",
    "700-italic": "https://fonts.gstatic.com/s/b612/v13/3Jn_SDDxiSz36juKoDWxTl0A.woff2",
    "700-normal": "https://fonts.gstatic.com/s/b612/v13/3Jn9SDDxiSz34oWXDDeBTA.woff2",
  },
} as const;

export type B612Weight = "400" | "700";
export type B612Style = "italic" | "normal";
export type B612Subset = "latin";
export type B612Options = GoogleFontOptions<B612Weight, B612Style, B612Subset>;

/**
 * B612 — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class B612 extends GoogleFont<B612Weight, B612Style, B612Subset> {
  constructor(options?: B612Options) {
    super(FAMILY, FACES, options);
  }
}
