// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Baloo 2";

const FACES = {
  "devanagari": {
    "400-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51ncANwr.woff2",
    "500-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51ncANwr.woff2",
    "600-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51ncANwr.woff2",
    "700-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51ncANwr.woff2",
    "800-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51ncANwr.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51jcAA.woff2",
    "500-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51jcAA.woff2",
    "600-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51jcAA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51jcAA.woff2",
    "800-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51jcAA.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51bcANwr.woff2",
    "500-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51bcANwr.woff2",
    "600-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51bcANwr.woff2",
    "700-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51bcANwr.woff2",
    "800-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51bcANwr.woff2",
  },
  "vietnamese": {
    "400-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51fcANwr.woff2",
    "500-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51fcANwr.woff2",
    "600-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51fcANwr.woff2",
    "700-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51fcANwr.woff2",
    "800-normal": "https://fonts.gstatic.com/s/baloo2/v23/wXKrE3kTposypRyd51fcANwr.woff2",
  },
} as const;

export type Baloo2Weight = "400" | "500" | "600" | "700" | "800";
export type Baloo2Style = "normal";
export type Baloo2Subset = "devanagari" | "latin" | "latin-ext" | "vietnamese";
export type Baloo2Options = GoogleFontOptions<Baloo2Weight, Baloo2Style, Baloo2Subset>;

/**
 * Baloo 2 — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Baloo2 extends GoogleFont<Baloo2Weight, Baloo2Style, Baloo2Subset> {
  constructor(options?: Baloo2Options) {
    super(FAMILY, FACES, options);
  }
}
