// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Barlow";

const FACES = {
  latin: {
    "100-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHtv4kjgoGqM7E_CfNY8H0JmA.woff2",
    "100-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHrv4kjgoGqM7E3b_s7wH8.woff2",
    "200-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfP04WouvTo.woff2",
    "200-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3w-os51os.woff2",
    "300-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfOQ4mouvTo.woff2",
    "300-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3p-ks51os.woff2",
    "400-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHrv4kjgoGqM7E_Cfs7wH8.woff2",
    "400-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHpv4kjgoGqM7E_DMs5.woff2",
    "500-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfPI42ouvTo.woff2",
    "500-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3_-gs51os.woff2",
    "600-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfPk5GouvTo.woff2",
    "600-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E30-8s51os.woff2",
    "700-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfOA5WouvTo.woff2",
    "700-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3t-4s51os.woff2",
    "800-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfOc5mouvTo.woff2",
    "800-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3q-0s51os.woff2",
    "900-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfO452ouvTo.woff2",
    "900-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3j-ws51os.woff2",
  },
  "latin-ext": {
    "100-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHtv4kjgoGqM7E_CfNY8HMJmAci.woff2",
    "100-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHrv4kjgoGqM7E3b_s1wH8RnA.woff2",
    "200-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfP04WogvTobdw.woff2",
    "200-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3w-os6VospT4.woff2",
    "300-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfOQ4mogvTobdw.woff2",
    "300-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3p-ks6VospT4.woff2",
    "400-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHrv4kjgoGqM7E_Cfs1wH8RnA.woff2",
    "400-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHpv4kjgoGqM7E_Ass52Hs.woff2",
    "500-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfPI42ogvTobdw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3_-gs6VospT4.woff2",
    "600-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfPk5GogvTobdw.woff2",
    "600-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E30-8s6VospT4.woff2",
    "700-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfOA5WogvTobdw.woff2",
    "700-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3t-4s6VospT4.woff2",
    "800-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfOc5mogvTobdw.woff2",
    "800-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3q-0s6VospT4.woff2",
    "900-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfO452ogvTobdw.woff2",
    "900-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3j-ws6VospT4.woff2",
  },
  vietnamese: {
    "100-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHtv4kjgoGqM7E_CfNY8HIJmAci.woff2",
    "100-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHrv4kjgoGqM7E3b_s0wH8RnA.woff2",
    "200-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfP04WohvTobdw.woff2",
    "200-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3w-os6FospT4.woff2",
    "300-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfOQ4mohvTobdw.woff2",
    "300-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3p-ks6FospT4.woff2",
    "400-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHrv4kjgoGqM7E_Cfs0wH8RnA.woff2",
    "400-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHpv4kjgoGqM7E_A8s52Hs.woff2",
    "500-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfPI42ohvTobdw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3_-gs6FospT4.woff2",
    "600-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfPk5GohvTobdw.woff2",
    "600-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E30-8s6FospT4.woff2",
    "700-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfOA5WohvTobdw.woff2",
    "700-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3t-4s6FospT4.woff2",
    "800-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfOc5mohvTobdw.woff2",
    "800-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3q-0s6FospT4.woff2",
    "900-italic": "https://fonts.gstatic.com/s/barlow/v13/7cHsv4kjgoGqM7E_CfO452ohvTobdw.woff2",
    "900-normal": "https://fonts.gstatic.com/s/barlow/v13/7cHqv4kjgoGqM7E3j-ws6FospT4.woff2",
  },
} as const;

export type BarlowWeight = "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900";
export type BarlowStyle = "italic" | "normal";
export type BarlowSubset = "latin" | "latin-ext" | "vietnamese";
export type BarlowOptions = GoogleFontOptions<BarlowWeight, BarlowStyle, BarlowSubset>;

/**
 * Barlow — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Barlow extends GoogleFont<BarlowWeight, BarlowStyle, BarlowSubset> {
  constructor(options?: BarlowOptions) {
    super(FAMILY, FACES, options);
  }
}
