// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Blaka Ink";

const FACES = {
  "arabic": {
    "400-normal": "https://fonts.gstatic.com/s/blakaink/v10/AlZy_zVVtpj22Znag2cRd335bB1boA.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/blakaink/v10/AlZy_zVVtpj22Znag2cRcn35BB4.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/blakaink/v10/AlZy_zVVtpj22Znag2cRfH35bB1boA.woff2",
  },
} as const;

export type BlakaInkWeight = "400";
export type BlakaInkStyle = "normal";
export type BlakaInkSubset = "arabic" | "latin" | "latin-ext";
export type BlakaInkOptions = GoogleFontOptions<BlakaInkWeight, BlakaInkStyle, BlakaInkSubset>;

/**
 * Blaka Ink — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class BlakaInk extends GoogleFont<BlakaInkWeight, BlakaInkStyle, BlakaInkSubset> {
  constructor(options?: BlakaInkOptions) {
    super(FAMILY, FACES, options);
  }
}
