// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Bokor";

const FACES = {
  khmer: {
    "400-normal": "https://fonts.gstatic.com/s/bokor/v32/m8JcjfpeeaqTiS2afojrcQ.woff2",
  },
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/bokor/v32/m8JcjfpeeaqTiS2Rfog.woff2",
  },
} as const;

export type BokorWeight = "400";
export type BokorStyle = "normal";
export type BokorSubset = "khmer" | "latin";
export type BokorOptions = GoogleFontOptions<BokorWeight, BokorStyle, BokorSubset>;

/**
 * Bokor — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Bokor extends GoogleFont<BokorWeight, BokorStyle, BokorSubset> {
  constructor(options?: BokorOptions) {
    super(FAMILY, FACES, options);
  }
}
