// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Borel";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/borel/v10/6qLOKZsftAPisjsmaSI.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/borel/v10/6qLOKZsftAPisjsoaSIXOg.woff2",
  },
  math: {
    "400-normal": "https://fonts.gstatic.com/s/borel/v10/6qLOKZsftAPisjtaaSIXOg.woff2",
  },
  symbols: {
    "400-normal": "https://fonts.gstatic.com/s/borel/v10/6qLOKZsftAPisjtIaSIXOg.woff2",
  },
  vietnamese: {
    "400-normal": "https://fonts.gstatic.com/s/borel/v10/6qLOKZsftAPisjspaSIXOg.woff2",
  },
} as const;

export type BorelWeight = "400";
export type BorelStyle = "normal";
export type BorelSubset = "latin" | "latin-ext" | "math" | "symbols" | "vietnamese";
export type BorelOptions = GoogleFontOptions<BorelWeight, BorelStyle, BorelSubset>;

/**
 * Borel — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Borel extends GoogleFont<BorelWeight, BorelStyle, BorelSubset> {
  constructor(options?: BorelOptions) {
    super(FAMILY, FACES, options);
  }
}
