// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Bpmf Zihi Kai Std";

const FACES = {
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/bpmfzihikaistd/v6/9XU_lIdmjlbGWCXAeHssPRoh5OLaAjzB7yI.woff2",
  },
  "latin-ext": {
    "400-normal":
      "https://fonts.gstatic.com/s/bpmfzihikaistd/v6/9XU_lIdmjlbGWCXAeHssPRoh5OLaAjzP7yIdfg.woff2",
  },
} as const;

export type BpmfZihiKaiStdWeight = "400";
export type BpmfZihiKaiStdStyle = "normal";
export type BpmfZihiKaiStdSubset = "latin" | "latin-ext";
export type BpmfZihiKaiStdOptions = GoogleFontOptions<
  BpmfZihiKaiStdWeight,
  BpmfZihiKaiStdStyle,
  BpmfZihiKaiStdSubset
>;

/**
 * Bpmf Zihi Kai Std — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class BpmfZihiKaiStd extends GoogleFont<
  BpmfZihiKaiStdWeight,
  BpmfZihiKaiStdStyle,
  BpmfZihiKaiStdSubset
> {
  constructor(options?: BpmfZihiKaiStdOptions) {
    super(FAMILY, FACES, options);
  }
}
