// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Carlito";

const FACES = {
  "cyrillic": {
    "400-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn_SDPw3m-pk039DDKxSl0AbuE.woff2",
    "400-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn9SDPw3m-pk039DDOBTEUE.woff2",
    "700-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn6SDPw3m-pk039DDK59XgVVcBG6Oo.woff2",
    "700-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn4SDPw3m-pk039BIykWX4lU9hC.woff2",
  },
  "cyrillic-ext": {
    "400-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn_SDPw3m-pk039DDKxQ10AbuE.woff2",
    "400-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn9SDPw3m-pk039DDqBTEUE.woff2",
    "700-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn6SDPw3m-pk039DDK59XgVXMBG6Oo.woff2",
    "700-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn4SDPw3m-pk039BIykWXclU9hC.woff2",
  },
  "greek": {
    "400-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn_SDPw3m-pk039DDKxTV0AbuE.woff2",
    "400-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn9SDPw3m-pk039DDSBTEUE.woff2",
    "700-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn6SDPw3m-pk039DDK59XgVUsBG6Oo.woff2",
    "700-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn4SDPw3m-pk039BIykWXklU9hC.woff2",
  },
  "greek-ext": {
    "400-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn_SDPw3m-pk039DDKxQl0AbuE.woff2",
    "400-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn9SDPw3m-pk039DDuBTEUE.woff2",
    "700-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn6SDPw3m-pk039DDK59XgVXcBG6Oo.woff2",
    "700-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn4SDPw3m-pk039BIykWXYlU9hC.woff2",
  },
  "latin": {
    "400-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn_SDPw3m-pk039DDKxTl0A.woff2",
    "400-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn9SDPw3m-pk039DDeBTA.woff2",
    "700-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn6SDPw3m-pk039DDK59XgVUcBG.woff2",
    "700-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn4SDPw3m-pk039BIykWXolUw.woff2",
  },
  "latin-ext": {
    "400-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn_SDPw3m-pk039DDKxQF0AbuE.woff2",
    "400-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn9SDPw3m-pk039DDmBTEUE.woff2",
    "700-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn6SDPw3m-pk039DDK59XgVX8BG6Oo.woff2",
    "700-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn4SDPw3m-pk039BIykWXQlU9hC.woff2",
  },
  "vietnamese": {
    "400-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn_SDPw3m-pk039DDKxQV0AbuE.woff2",
    "400-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn9SDPw3m-pk039DDiBTEUE.woff2",
    "700-italic": "https://fonts.gstatic.com/s/carlito/v4/3Jn6SDPw3m-pk039DDK59XgVXsBG6Oo.woff2",
    "700-normal": "https://fonts.gstatic.com/s/carlito/v4/3Jn4SDPw3m-pk039BIykWXUlU9hC.woff2",
  },
} as const;

export type CarlitoWeight = "400" | "700";
export type CarlitoStyle = "italic" | "normal";
export type CarlitoSubset = "cyrillic" | "cyrillic-ext" | "greek" | "greek-ext" | "latin" | "latin-ext" | "vietnamese";
export type CarlitoOptions = GoogleFontOptions<CarlitoWeight, CarlitoStyle, CarlitoSubset>;

/**
 * Carlito — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Carlito extends GoogleFont<CarlitoWeight, CarlitoStyle, CarlitoSubset> {
  constructor(options?: CarlitoOptions) {
    super(FAMILY, FACES, options);
  }
}
