// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Cascadia Code";

const FACES = {
  "arabic": {
    "200-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rsBElg4M.woff2",
    "200-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aD7btwkh.woff2",
    "300-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rsBElg4M.woff2",
    "300-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aD7btwkh.woff2",
    "400-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rsBElg4M.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aD7btwkh.woff2",
    "500-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rsBElg4M.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aD7btwkh.woff2",
    "600-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rsBElg4M.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aD7btwkh.woff2",
    "700-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rsBElg4M.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aD7btwkh.woff2",
  },
  "braille": {
    "200-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rGzAAvroI.woff2",
    "200-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aJX6kjQYug.woff2",
    "300-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rGzAAvroI.woff2",
    "300-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aJX6kjQYug.woff2",
    "400-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rGzAAvroI.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aJX6kjQYug.woff2",
    "500-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rGzAAvroI.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aJX6kjQYug.woff2",
    "600-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rGzAAvroI.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aJX6kjQYug.woff2",
    "700-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rGzAAvroI.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aJX6kjQYug.woff2",
  },
  "cyrillic": {
    "200-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rsRElg4M.woff2",
    "200-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aD_btwkh.woff2",
    "300-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rsRElg4M.woff2",
    "300-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aD_btwkh.woff2",
    "400-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rsRElg4M.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aD_btwkh.woff2",
    "500-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rsRElg4M.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aD_btwkh.woff2",
    "600-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rsRElg4M.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aD_btwkh.woff2",
    "700-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rsRElg4M.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aD_btwkh.woff2",
  },
  "cyrillic-ext": {
    "200-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruBElg4M.woff2",
    "200-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDbbtwkh.woff2",
    "300-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruBElg4M.woff2",
    "300-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDbbtwkh.woff2",
    "400-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruBElg4M.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDbbtwkh.woff2",
    "500-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruBElg4M.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDbbtwkh.woff2",
    "600-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruBElg4M.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDbbtwkh.woff2",
    "700-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruBElg4M.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDbbtwkh.woff2",
  },
  "greek": {
    "200-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rthElg4M.woff2",
    "200-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDjbtwkh.woff2",
    "300-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rthElg4M.woff2",
    "300-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDjbtwkh.woff2",
    "400-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rthElg4M.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDjbtwkh.woff2",
    "500-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rthElg4M.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDjbtwkh.woff2",
    "600-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rthElg4M.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDjbtwkh.woff2",
    "700-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rthElg4M.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDjbtwkh.woff2",
  },
  "hebrew": {
    "200-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rtxElg4M.woff2",
    "200-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDnbtwkh.woff2",
    "300-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rtxElg4M.woff2",
    "300-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDnbtwkh.woff2",
    "400-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rtxElg4M.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDnbtwkh.woff2",
    "500-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rtxElg4M.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDnbtwkh.woff2",
    "600-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rtxElg4M.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDnbtwkh.woff2",
    "700-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rtxElg4M.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDnbtwkh.woff2",
  },
  "latin": {
    "200-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rtREl.woff2",
    "200-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDvbtw.woff2",
    "300-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rtREl.woff2",
    "300-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDvbtw.woff2",
    "400-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rtREl.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDvbtw.woff2",
    "500-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rtREl.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDvbtw.woff2",
    "600-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rtREl.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDvbtw.woff2",
    "700-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rtREl.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDvbtw.woff2",
  },
  "latin-ext": {
    "200-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruxElg4M.woff2",
    "200-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDXbtwkh.woff2",
    "300-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruxElg4M.woff2",
    "300-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDXbtwkh.woff2",
    "400-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruxElg4M.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDXbtwkh.woff2",
    "500-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruxElg4M.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDXbtwkh.woff2",
    "600-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruxElg4M.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDXbtwkh.woff2",
    "700-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruxElg4M.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDXbtwkh.woff2",
  },
  "symbols2": {
    "200-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rDzAAvroI.woff2",
    "200-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aIH6kjQYug.woff2",
    "300-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rDzAAvroI.woff2",
    "300-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aIH6kjQYug.woff2",
    "400-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rDzAAvroI.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aIH6kjQYug.woff2",
    "500-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rDzAAvroI.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aIH6kjQYug.woff2",
    "600-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rDzAAvroI.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aIH6kjQYug.woff2",
    "700-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7rDzAAvroI.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aIH6kjQYug.woff2",
  },
  "vietnamese": {
    "200-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruhElg4M.woff2",
    "200-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDTbtwkh.woff2",
    "300-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruhElg4M.woff2",
    "300-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDTbtwkh.woff2",
    "400-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruhElg4M.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDTbtwkh.woff2",
    "500-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruhElg4M.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDTbtwkh.woff2",
    "600-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruhElg4M.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDTbtwkh.woff2",
    "700-italic": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcyB6-zq5zxD57cT5s916v3aD7ruhElg4M.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cascadiacode/v5/qWcsB6-zq5zxD57cT5s916v3aDTbtwkh.woff2",
  },
} as const;

export type CascadiaCodeWeight = "200" | "300" | "400" | "500" | "600" | "700";
export type CascadiaCodeStyle = "italic" | "normal";
export type CascadiaCodeSubset = "arabic" | "braille" | "cyrillic" | "cyrillic-ext" | "greek" | "hebrew" | "latin" | "latin-ext" | "symbols2" | "vietnamese";
export type CascadiaCodeOptions = GoogleFontOptions<CascadiaCodeWeight, CascadiaCodeStyle, CascadiaCodeSubset>;

/**
 * Cascadia Code — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class CascadiaCode extends GoogleFont<CascadiaCodeWeight, CascadiaCodeStyle, CascadiaCodeSubset> {
  constructor(options?: CascadiaCodeOptions) {
    super(FAMILY, FACES, options);
  }
}
