// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Cause";

const FACES = {
  "latin": {
    "100-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NTbJE.woff2",
    "200-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NTbJE.woff2",
    "300-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NTbJE.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NTbJE.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NTbJE.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NTbJE.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NTbJE.woff2",
    "800-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NTbJE.woff2",
    "900-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NTbJE.woff2",
  },
  "latin-ext": {
    "100-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NdbJHPBw.woff2",
    "200-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NdbJHPBw.woff2",
    "300-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NdbJHPBw.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NdbJHPBw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NdbJHPBw.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NdbJHPBw.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NdbJHPBw.woff2",
    "800-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NdbJHPBw.woff2",
    "900-normal": "https://fonts.gstatic.com/s/cause/v2/or3sQ6760-mf03NdbJHPBw.woff2",
  },
} as const;

export type CauseWeight = "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900";
export type CauseStyle = "normal";
export type CauseSubset = "latin" | "latin-ext";
export type CauseOptions = GoogleFontOptions<CauseWeight, CauseStyle, CauseSubset>;

/**
 * Cause — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Cause extends GoogleFont<CauseWeight, CauseStyle, CauseSubset> {
  constructor(options?: CauseOptions) {
    super(FAMILY, FACES, options);
  }
}
