// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Chela One";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/chelaone/v22/6ae-4KC7Uqgdz_JZdPIC2FHX.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/chelaone/v22/6ae-4KC7Uqgdz_JZdPIC1lHXBTM.woff2",
  },
} as const;

export type ChelaOneWeight = "400";
export type ChelaOneStyle = "normal";
export type ChelaOneSubset = "latin" | "latin-ext";
export type ChelaOneOptions = GoogleFontOptions<ChelaOneWeight, ChelaOneStyle, ChelaOneSubset>;

/**
 * Chela One — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class ChelaOne extends GoogleFont<ChelaOneWeight, ChelaOneStyle, ChelaOneSubset> {
  constructor(options?: ChelaOneOptions) {
    super(FAMILY, FACES, options);
  }
}
