// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Chewy";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/chewy/v18/uK_94ruUb-k-wn52KjI.woff2",
  },
} as const;

export type ChewyWeight = "400";
export type ChewyStyle = "normal";
export type ChewySubset = "latin";
export type ChewyOptions = GoogleFontOptions<ChewyWeight, ChewyStyle, ChewySubset>;

/**
 * Chewy — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Chewy extends GoogleFont<ChewyWeight, ChewyStyle, ChewySubset> {
  constructor(options?: ChewyOptions) {
    super(FAMILY, FACES, options);
  }
}
