// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Coda";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/coda/v22/SLXHc1jY5nQ8FUUGaw.woff2",
    "800-normal": "https://fonts.gstatic.com/s/coda/v22/SLXIc1jY5nQ8HeIgfpmswg.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/coda/v22/SLXHc1jY5nQ8FUsGa6aN.woff2",
    "800-normal": "https://fonts.gstatic.com/s/coda/v22/SLXIc1jY5nQ8HeIgfpeswut1.woff2",
  },
} as const;

export type CodaWeight = "400" | "800";
export type CodaStyle = "normal";
export type CodaSubset = "latin" | "latin-ext";
export type CodaOptions = GoogleFontOptions<CodaWeight, CodaStyle, CodaSubset>;

/**
 * Coda — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Coda extends GoogleFont<CodaWeight, CodaStyle, CodaSubset> {
  constructor(options?: CodaOptions) {
    super(FAMILY, FACES, options);
  }
}
