// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Content";

const FACES = {
  "khmer": {
    "400-normal": "https://fonts.gstatic.com/s/content/v27/zrfl0HLayePhU_AwYaz4Iw.woff2",
    "700-normal": "https://fonts.gstatic.com/s/content/v27/zrfg0HLayePhU_AwaRzdNibVWQ.woff2",
  },
} as const;

export type ContentWeight = "400" | "700";
export type ContentStyle = "normal";
export type ContentSubset = "khmer";
export type ContentOptions = GoogleFontOptions<ContentWeight, ContentStyle, ContentSubset>;

/**
 * Content — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Content extends GoogleFont<ContentWeight, ContentStyle, ContentSubset> {
  constructor(options?: ContentOptions) {
    super(FAMILY, FACES, options);
  }
}
