// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Cormorant Unicase";

const FACES = {
  "cyrillic": {
    "300-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9N_ttcs5m2EDQ.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_QiZUaILtOqhqgDeXoF_n1_fTGX9vQlMIXxw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9Mnt9cs5m2EDQ.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9MLsNcs5m2EDQ.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9Nvsdcs5m2EDQ.woff2",
  },
  "cyrillic-ext": {
    "300-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9N_ttcl5m2EDQ.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_QiZUaILtOqhqgDeXoF_n1_fTGX9vZlMIXxw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9Mnt9cl5m2EDQ.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9MLsNcl5m2EDQ.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9Nvsdcl5m2EDQ.woff2",
  },
  "latin": {
    "300-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9N_ttco5m0.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_QiZUaILtOqhqgDeXoF_n1_fTGX9vUlMI.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9Mnt9co5m0.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9MLsNco5m0.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9Nvsdco5m0.woff2",
  },
  "latin-ext": {
    "300-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9N_ttcm5m2EDQ.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_QiZUaILtOqhqgDeXoF_n1_fTGX9valMIXxw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9Mnt9cm5m2EDQ.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9MLsNcm5m2EDQ.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9Nvsdcm5m2EDQ.woff2",
  },
  "vietnamese": {
    "300-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9N_ttcn5m2EDQ.woff2",
    "400-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_QiZUaILtOqhqgDeXoF_n1_fTGX9vblMIXxw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9Mnt9cn5m2EDQ.woff2",
    "600-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9MLsNcn5m2EDQ.woff2",
    "700-normal": "https://fonts.gstatic.com/s/cormorantunicase/v25/HI_ViZUaILtOqhqgDeXoF_n1_fTGX9Nvsdcn5m2EDQ.woff2",
  },
} as const;

export type CormorantUnicaseWeight = "300" | "400" | "500" | "600" | "700";
export type CormorantUnicaseStyle = "normal";
export type CormorantUnicaseSubset = "cyrillic" | "cyrillic-ext" | "latin" | "latin-ext" | "vietnamese";
export type CormorantUnicaseOptions = GoogleFontOptions<CormorantUnicaseWeight, CormorantUnicaseStyle, CormorantUnicaseSubset>;

/**
 * Cormorant Unicase — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class CormorantUnicase extends GoogleFont<CormorantUnicaseWeight, CormorantUnicaseStyle, CormorantUnicaseSubset> {
  constructor(options?: CormorantUnicaseOptions) {
    super(FAMILY, FACES, options);
  }
}
