// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Coustard";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/coustard/v19/3XFpErgg3YsZ5fqUU-UIt2Q.woff2",
    "900-normal": "https://fonts.gstatic.com/s/coustard/v19/3XFuErgg3YsZ5fqUU-2LkHHhZfk.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/coustard/v19/3XFpErgg3YsZ5fqUU-UGt2TeRA.woff2",
    "900-normal": "https://fonts.gstatic.com/s/coustard/v19/3XFuErgg3YsZ5fqUU-2LkHHvZfnk3Q.woff2",
  },
} as const;

export type CoustardWeight = "400" | "900";
export type CoustardStyle = "normal";
export type CoustardSubset = "latin" | "latin-ext";
export type CoustardOptions = GoogleFontOptions<CoustardWeight, CoustardStyle, CoustardSubset>;

/**
 * Coustard — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Coustard extends GoogleFont<CoustardWeight, CoustardStyle, CoustardSubset> {
  constructor(options?: CoustardOptions) {
    super(FAMILY, FACES, options);
  }
}
