// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Dela Gothic One";

const FACES = {
  cyrillic: {
    "400-normal":
      "https://fonts.gstatic.com/s/delagothicone/v19/hESp6XxvMDRA-2eD0lXpDa6QkBA2RkEIcAk.woff2",
  },
  greek: {
    "400-normal":
      "https://fonts.gstatic.com/s/delagothicone/v19/hESp6XxvMDRA-2eD0lXpDa6QkBA2QUEIcAk.woff2",
  },
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/delagothicone/v19/hESp6XxvMDRA-2eD0lXpDa6QkBA2QkEI.woff2",
  },
  "latin-ext": {
    "400-normal":
      "https://fonts.gstatic.com/s/delagothicone/v19/hESp6XxvMDRA-2eD0lXpDa6QkBA2TEEIcAk.woff2",
  },
  vietnamese: {
    "400-normal":
      "https://fonts.gstatic.com/s/delagothicone/v19/hESp6XxvMDRA-2eD0lXpDa6QkBA2TUEIcAk.woff2",
  },
} as const;

export type DelaGothicOneWeight = "400";
export type DelaGothicOneStyle = "normal";
export type DelaGothicOneSubset = "cyrillic" | "greek" | "latin" | "latin-ext" | "vietnamese";
export type DelaGothicOneOptions = GoogleFontOptions<
  DelaGothicOneWeight,
  DelaGothicOneStyle,
  DelaGothicOneSubset
>;

/**
 * Dela Gothic One — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class DelaGothicOne extends GoogleFont<
  DelaGothicOneWeight,
  DelaGothicOneStyle,
  DelaGothicOneSubset
> {
  constructor(options?: DelaGothicOneOptions) {
    super(FAMILY, FACES, options);
  }
}
