// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Edu NSW ACT Cursive";

const FACES = {
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/edunswactcursive/v3/xn78YGUw02PnIPEjskHSG_2fCaz9DzhQR8jl3A.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/edunswactcursive/v3/xn78YGUw02PnIPEjskHSG_2fCaz9DzhQR8jl3A.woff2",
    "600-normal":
      "https://fonts.gstatic.com/s/edunswactcursive/v3/xn78YGUw02PnIPEjskHSG_2fCaz9DzhQR8jl3A.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/edunswactcursive/v3/xn78YGUw02PnIPEjskHSG_2fCaz9DzhQR8jl3A.woff2",
  },
  "latin-ext": {
    "400-normal":
      "https://fonts.gstatic.com/s/edunswactcursive/v3/xn78YGUw02PnIPEjskHSG_2fCaz9DzhQR8bl3IT4.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/edunswactcursive/v3/xn78YGUw02PnIPEjskHSG_2fCaz9DzhQR8bl3IT4.woff2",
    "600-normal":
      "https://fonts.gstatic.com/s/edunswactcursive/v3/xn78YGUw02PnIPEjskHSG_2fCaz9DzhQR8bl3IT4.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/edunswactcursive/v3/xn78YGUw02PnIPEjskHSG_2fCaz9DzhQR8bl3IT4.woff2",
  },
} as const;

export type EduNSWACTCursiveWeight = "400" | "500" | "600" | "700";
export type EduNSWACTCursiveStyle = "normal";
export type EduNSWACTCursiveSubset = "latin" | "latin-ext";
export type EduNSWACTCursiveOptions = GoogleFontOptions<
  EduNSWACTCursiveWeight,
  EduNSWACTCursiveStyle,
  EduNSWACTCursiveSubset
>;

/**
 * Edu NSW ACT Cursive — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class EduNSWACTCursive extends GoogleFont<
  EduNSWACTCursiveWeight,
  EduNSWACTCursiveStyle,
  EduNSWACTCursiveSubset
> {
  constructor(options?: EduNSWACTCursiveOptions) {
    super(FAMILY, FACES, options);
  }
}
