// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Encode Sans SC";

const FACES = {
  "latin": {
    "100-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3ukYU.woff2",
    "200-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3ukYU.woff2",
    "300-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3ukYU.woff2",
    "400-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3ukYU.woff2",
    "500-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3ukYU.woff2",
    "600-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3ukYU.woff2",
    "700-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3ukYU.woff2",
    "800-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3ukYU.woff2",
    "900-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3ukYU.woff2",
  },
  "latin-ext": {
    "100-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tEYUmKI.woff2",
    "200-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tEYUmKI.woff2",
    "300-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tEYUmKI.woff2",
    "400-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tEYUmKI.woff2",
    "500-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tEYUmKI.woff2",
    "600-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tEYUmKI.woff2",
    "700-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tEYUmKI.woff2",
    "800-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tEYUmKI.woff2",
    "900-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tEYUmKI.woff2",
  },
  "vietnamese": {
    "100-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tUYUmKI.woff2",
    "200-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tUYUmKI.woff2",
    "300-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tUYUmKI.woff2",
    "400-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tUYUmKI.woff2",
    "500-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tUYUmKI.woff2",
    "600-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tUYUmKI.woff2",
    "700-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tUYUmKI.woff2",
    "800-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tUYUmKI.woff2",
    "900-normal": "https://fonts.gstatic.com/s/encodesanssc/v14/jVye7nLwCGzQ9zE7ZyRg0QRXHPZc_uUA6Kb3VJWLE_P3tUYUmKI.woff2",
  },
} as const;

export type EncodeSansSCWeight = "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900";
export type EncodeSansSCStyle = "normal";
export type EncodeSansSCSubset = "latin" | "latin-ext" | "vietnamese";
export type EncodeSansSCOptions = GoogleFontOptions<EncodeSansSCWeight, EncodeSansSCStyle, EncodeSansSCSubset>;

/**
 * Encode Sans SC — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class EncodeSansSC extends GoogleFont<EncodeSansSCWeight, EncodeSansSCStyle, EncodeSansSCSubset> {
  constructor(options?: EncodeSansSCOptions) {
    super(FAMILY, FACES, options);
  }
}
