// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Englebert";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/englebert/v24/xn7iYH8w2XGrC8AR4HSBSP3Z.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/englebert/v24/xn7iYH8w2XGrC8AR4HSBRv3ZRN8.woff2",
  },
} as const;

export type EnglebertWeight = "400";
export type EnglebertStyle = "normal";
export type EnglebertSubset = "latin" | "latin-ext";
export type EnglebertOptions = GoogleFontOptions<EnglebertWeight, EnglebertStyle, EnglebertSubset>;

/**
 * Englebert — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Englebert extends GoogleFont<
  EnglebertWeight,
  EnglebertStyle,
  EnglebertSubset
> {
  constructor(options?: EnglebertOptions) {
    super(FAMILY, FACES, options);
  }
}
