// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Fira Mono";

const FACES = {
  "cyrillic": {
    "400-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bX2SlFPv1weGeLZDtgIv7SodY.woff2",
    "500-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDto1d3HmvfUWZA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDtondvHmvfUWZA.woff2",
  },
  "cyrillic-ext": {
    "400-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bX2SlFPv1weGeLZDtgK_7SodY.woff2",
    "500-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDto1d3Hk_fUWZA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDtondvHk_fUWZA.woff2",
  },
  "greek": {
    "400-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bX2SlFPv1weGeLZDtgJf7SodY.woff2",
    "500-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDto1d3HnffUWZA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDtondvHnffUWZA.woff2",
  },
  "greek-ext": {
    "400-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bX2SlFPv1weGeLZDtgKv7SodY.woff2",
    "500-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDto1d3HkvfUWZA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDtondvHkvfUWZA.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bX2SlFPv1weGeLZDtgJv7S.woff2",
    "500-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDto1d3HnvfU.woff2",
    "700-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDtondvHnvfU.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bX2SlFPv1weGeLZDtgKP7SodY.woff2",
    "500-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDto1d3HkPfUWZA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDtondvHkPfUWZA.woff2",
  },
  "symbols2": {
    "400-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bX2SlFPv1weGeLZDtgnN_3nO_Q.woff2",
    "500-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDto1d3HJNbxZKlI.woff2",
    "700-normal": "https://fonts.gstatic.com/s/firamono/v16/N0bS2SlFPv1weGeLZDtondvHJNbxZKlI.woff2",
  },
} as const;

export type FiraMonoWeight = "400" | "500" | "700";
export type FiraMonoStyle = "normal";
export type FiraMonoSubset = "cyrillic" | "cyrillic-ext" | "greek" | "greek-ext" | "latin" | "latin-ext" | "symbols2";
export type FiraMonoOptions = GoogleFontOptions<FiraMonoWeight, FiraMonoStyle, FiraMonoSubset>;

/**
 * Fira Mono — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class FiraMono extends GoogleFont<FiraMonoWeight, FiraMonoStyle, FiraMonoSubset> {
  constructor(options?: FiraMonoOptions) {
    super(FAMILY, FACES, options);
  }
}
