// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Flavors";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/flavors/v28/FBV2dDrhxqmveJTpXkvvNw.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/flavors/v28/FBV2dDrhxqmveJTpXkXvN5kG.woff2",
  },
} as const;

export type FlavorsWeight = "400";
export type FlavorsStyle = "normal";
export type FlavorsSubset = "latin" | "latin-ext";
export type FlavorsOptions = GoogleFontOptions<FlavorsWeight, FlavorsStyle, FlavorsSubset>;

/**
 * Flavors — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Flavors extends GoogleFont<FlavorsWeight, FlavorsStyle, FlavorsSubset> {
  constructor(options?: FlavorsOptions) {
    super(FAMILY, FACES, options);
  }
}
