// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Flow Rounded";

const FACES = {
  "cyrillic": {
    "400-normal": "https://fonts.gstatic.com/s/flowrounded/v15/-zki91mtwsU9qlLiGwD4oQXHop__buo.woff2",
  },
  "cyrillic-ext": {
    "400-normal": "https://fonts.gstatic.com/s/flowrounded/v15/-zki91mtwsU9qlLiGwD4oQXHq5__buo.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/flowrounded/v15/-zki91mtwsU9qlLiGwD4oQXHpp__.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/flowrounded/v15/-zki91mtwsU9qlLiGwD4oQXHqJ__buo.woff2",
  },
  "vietnamese": {
    "400-normal": "https://fonts.gstatic.com/s/flowrounded/v15/-zki91mtwsU9qlLiGwD4oQXHqZ__buo.woff2",
  },
} as const;

export type FlowRoundedWeight = "400";
export type FlowRoundedStyle = "normal";
export type FlowRoundedSubset = "cyrillic" | "cyrillic-ext" | "latin" | "latin-ext" | "vietnamese";
export type FlowRoundedOptions = GoogleFontOptions<FlowRoundedWeight, FlowRoundedStyle, FlowRoundedSubset>;

/**
 * Flow Rounded — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class FlowRounded extends GoogleFont<FlowRoundedWeight, FlowRoundedStyle, FlowRoundedSubset> {
  constructor(options?: FlowRoundedOptions) {
    super(FAMILY, FACES, options);
  }
}
