// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Fresca";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/fresca/v24/6ae94K--SKgCzbMGHbcX.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/fresca/v24/6ae94K--SKgCzbMGE7cX53A.woff2",
  },
} as const;

export type FrescaWeight = "400";
export type FrescaStyle = "normal";
export type FrescaSubset = "latin" | "latin-ext";
export type FrescaOptions = GoogleFontOptions<FrescaWeight, FrescaStyle, FrescaSubset>;

/**
 * Fresca — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Fresca extends GoogleFont<FrescaWeight, FrescaStyle, FrescaSubset> {
  constructor(options?: FrescaOptions) {
    super(FAMILY, FACES, options);
  }
}
