// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Fustat";

const FACES = {
  arabic: {
    "200-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLTfJCkyo.woff2",
    "300-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLTfJCkyo.woff2",
    "400-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLTfJCkyo.woff2",
    "500-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLTfJCkyo.woff2",
    "600-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLTfJCkyo.woff2",
    "700-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLTfJCkyo.woff2",
    "800-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLTfJCkyo.woff2",
  },
  latin: {
    "200-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLSPJC.woff2",
    "300-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLSPJC.woff2",
    "400-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLSPJC.woff2",
    "500-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLSPJC.woff2",
    "600-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLSPJC.woff2",
    "700-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLSPJC.woff2",
    "800-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLSPJC.woff2",
  },
  "latin-ext": {
    "200-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLRvJCkyo.woff2",
    "300-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLRvJCkyo.woff2",
    "400-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLRvJCkyo.woff2",
    "500-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLRvJCkyo.woff2",
    "600-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLRvJCkyo.woff2",
    "700-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLRvJCkyo.woff2",
    "800-normal": "https://fonts.gstatic.com/s/fustat/v4/NaPZcZ_aHO9Iy5tLRvJCkyo.woff2",
  },
} as const;

export type FustatWeight = "200" | "300" | "400" | "500" | "600" | "700" | "800";
export type FustatStyle = "normal";
export type FustatSubset = "arabic" | "latin" | "latin-ext";
export type FustatOptions = GoogleFontOptions<FustatWeight, FustatStyle, FustatSubset>;

/**
 * Fustat — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Fustat extends GoogleFont<FustatWeight, FustatStyle, FustatSubset> {
  constructor(options?: FustatOptions) {
    super(FAMILY, FACES, options);
  }
}
