// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Ga Maamli";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/gamaamli/v3/uU9NCBsQ4c-DPW1Yo3rh3dSD.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/gamaamli/v3/uU9NCBsQ4c-DPW1Yo3rh09SDulI.woff2",
  },
  "vietnamese": {
    "400-normal": "https://fonts.gstatic.com/s/gamaamli/v3/uU9NCBsQ4c-DPW1Yo3rh0tSDulI.woff2",
  },
} as const;

export type GaMaamliWeight = "400";
export type GaMaamliStyle = "normal";
export type GaMaamliSubset = "latin" | "latin-ext" | "vietnamese";
export type GaMaamliOptions = GoogleFontOptions<GaMaamliWeight, GaMaamliStyle, GaMaamliSubset>;

/**
 * Ga Maamli — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class GaMaamli extends GoogleFont<GaMaamliWeight, GaMaamliStyle, GaMaamliSubset> {
  constructor(options?: GaMaamliOptions) {
    super(FAMILY, FACES, options);
  }
}
