// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Gayathri";

const FACES = {
  latin: {
    "100-normal": "https://fonts.gstatic.com/s/gayathri/v20/MCoWzAb429DbBilWLLhcypzYAg.woff2",
    "400-normal": "https://fonts.gstatic.com/s/gayathri/v20/MCoQzAb429DbBilWLLA_-p4.woff2",
    "700-normal": "https://fonts.gstatic.com/s/gayathri/v20/MCoXzAb429DbBilWLLiE34v_J_U.woff2",
  },
  malayalam: {
    "100-normal": "https://fonts.gstatic.com/s/gayathri/v20/MCoWzAb429DbBilWLLhcyoTYAsgA.woff2",
    "400-normal": "https://fonts.gstatic.com/s/gayathri/v20/MCoQzAb429DbBilWLLAn-p7ABg.woff2",
    "700-normal": "https://fonts.gstatic.com/s/gayathri/v20/MCoXzAb429DbBilWLLiE34vnJ_U5wA.woff2",
  },
} as const;

export type GayathriWeight = "100" | "400" | "700";
export type GayathriStyle = "normal";
export type GayathriSubset = "latin" | "malayalam";
export type GayathriOptions = GoogleFontOptions<GayathriWeight, GayathriStyle, GayathriSubset>;

/**
 * Gayathri — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Gayathri extends GoogleFont<GayathriWeight, GayathriStyle, GayathriSubset> {
  constructor(options?: GayathriOptions) {
    super(FAMILY, FACES, options);
  }
}
