// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Geostar";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/geostar/v27/sykz-yx4n701VLOfhS23-w.woff2",
  },
} as const;

export type GeostarWeight = "400";
export type GeostarStyle = "normal";
export type GeostarSubset = "latin";
export type GeostarOptions = GoogleFontOptions<GeostarWeight, GeostarStyle, GeostarSubset>;

/**
 * Geostar — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Geostar extends GoogleFont<GeostarWeight, GeostarStyle, GeostarSubset> {
  constructor(options?: GeostarOptions) {
    super(FAMILY, FACES, options);
  }
}
