// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "GFS Didot";

const FACES = {
  greek: {
    "400-normal": "https://fonts.gstatic.com/s/gfsdidot/v18/Jqzh5TybZ9vZMWFssvwSE-3HJSA.woff2",
  },
  "greek-ext": {
    "400-normal": "https://fonts.gstatic.com/s/gfsdidot/v18/Jqzh5TybZ9vZMWFssvwSHO3HJSA.woff2",
  },
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/gfsdidot/v18/Jqzh5TybZ9vZMWFssvwSEO3H.woff2",
  },
  vietnamese: {
    "400-normal": "https://fonts.gstatic.com/s/gfsdidot/v18/Jqzh5TybZ9vZMWFssvwSH-3HJSA.woff2",
  },
} as const;

export type GFSDidotWeight = "400";
export type GFSDidotStyle = "normal";
export type GFSDidotSubset = "greek" | "greek-ext" | "latin" | "vietnamese";
export type GFSDidotOptions = GoogleFontOptions<GFSDidotWeight, GFSDidotStyle, GFSDidotSubset>;

/**
 * GFS Didot — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class GFSDidot extends GoogleFont<GFSDidotWeight, GFSDidotStyle, GFSDidotSubset> {
  constructor(options?: GFSDidotOptions) {
    super(FAMILY, FACES, options);
  }
}
