// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Gloock";

const FACES = {
  "cyrillic-ext": {
    "400-normal": "https://fonts.gstatic.com/s/gloock/v8/Iurb6YFw84WUY4NJhRakNrc.woff2",
  },
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/gloock/v8/Iurb6YFw84WUY4NJiBak.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/gloock/v8/Iurb6YFw84WUY4NJhhakNrc.woff2",
  },
} as const;

export type GloockWeight = "400";
export type GloockStyle = "normal";
export type GloockSubset = "cyrillic-ext" | "latin" | "latin-ext";
export type GloockOptions = GoogleFontOptions<GloockWeight, GloockStyle, GloockSubset>;

/**
 * Gloock — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Gloock extends GoogleFont<GloockWeight, GloockStyle, GloockSubset> {
  constructor(options?: GloockOptions) {
    super(FAMILY, FACES, options);
  }
}
