// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Gochi Hand";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/gochihand/v25/hES06XlsOjtJsgCkx1Pkfon_-w.woff2",
  },
} as const;

export type GochiHandWeight = "400";
export type GochiHandStyle = "normal";
export type GochiHandSubset = "latin";
export type GochiHandOptions = GoogleFontOptions<GochiHandWeight, GochiHandStyle, GochiHandSubset>;

/**
 * Gochi Hand — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class GochiHand extends GoogleFont<GochiHandWeight, GochiHandStyle, GochiHandSubset> {
  constructor(options?: GochiHandOptions) {
    super(FAMILY, FACES, options);
  }
}
