// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Gulzar";

const FACES = {
  arabic: {
    "400-normal": "https://fonts.gstatic.com/s/gulzar/v14/Wnz6HAc9eB3HB2I7YzYYmg8.woff2",
  },
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/gulzar/v14/Wnz6HAc9eB3HB2I7ZjYY.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/gulzar/v14/Wnz6HAc9eB3HB2I7aDYYmg8.woff2",
  },
} as const;

export type GulzarWeight = "400";
export type GulzarStyle = "normal";
export type GulzarSubset = "arabic" | "latin" | "latin-ext";
export type GulzarOptions = GoogleFontOptions<GulzarWeight, GulzarStyle, GulzarSubset>;

/**
 * Gulzar — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Gulzar extends GoogleFont<GulzarWeight, GulzarStyle, GulzarSubset> {
  constructor(options?: GulzarOptions) {
    super(FAMILY, FACES, options);
  }
}
