// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Hachi Maru Pop";

const FACES = {
  cyrillic: {
    "400-normal":
      "https://fonts.gstatic.com/s/hachimarupop/v23/HI_TiYoRLqpLrEiMAuO9Ysfz7oW2Gs7rtQ.woff2",
  },
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/hachimarupop/v23/HI_TiYoRLqpLrEiMAuO9Ysfz7oWyGs4.woff2",
  },
  "latin-ext": {
    "400-normal":
      "https://fonts.gstatic.com/s/hachimarupop/v23/HI_TiYoRLqpLrEiMAuO9Ysfz7oW8Gs7rtQ.woff2",
  },
} as const;

export type HachiMaruPopWeight = "400";
export type HachiMaruPopStyle = "normal";
export type HachiMaruPopSubset = "cyrillic" | "latin" | "latin-ext";
export type HachiMaruPopOptions = GoogleFontOptions<
  HachiMaruPopWeight,
  HachiMaruPopStyle,
  HachiMaruPopSubset
>;

/**
 * Hachi Maru Pop — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class HachiMaruPop extends GoogleFont<
  HachiMaruPopWeight,
  HachiMaruPopStyle,
  HachiMaruPopSubset
> {
  constructor(options?: HachiMaruPopOptions) {
    super(FAMILY, FACES, options);
  }
}
