// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Honk";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/honk/v6/m8J7jftUea-XwTaemClumrBQbmvynOmXBji9zFhHRr8WFgV7pLFM.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/honk/v6/m8J7jftUea-XwTaemClumrBQbmvynOmXBji9zFhHRr8WFgV7qrFMSpQ.woff2",
  },
  "math": {
    "400-normal": "https://fonts.gstatic.com/s/honk/v6/m8J7jftUea-XwTaemClumrBQbmvynOmXBji9zFhHRr8WFgV72LFMSpQ.woff2",
  },
  "symbols": {
    "400-normal": "https://fonts.gstatic.com/s/honk/v6/m8J7jftUea-XwTaemClumrBQbmvynOmXBji9zFhHRr8WFgV7yrFMSpQ.woff2",
  },
  "vietnamese": {
    "400-normal": "https://fonts.gstatic.com/s/honk/v6/m8J7jftUea-XwTaemClumrBQbmvynOmXBji9zFhHRr8WFgV7q7FMSpQ.woff2",
  },
} as const;

export type HonkWeight = "400";
export type HonkStyle = "normal";
export type HonkSubset = "latin" | "latin-ext" | "math" | "symbols" | "vietnamese";
export type HonkOptions = GoogleFontOptions<HonkWeight, HonkStyle, HonkSubset>;

/**
 * Honk — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Honk extends GoogleFont<HonkWeight, HonkStyle, HonkSubset> {
  constructor(options?: HonkOptions) {
    super(FAMILY, FACES, options);
  }
}
