// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Hubballi";

const FACES = {
  "kannada": {
    "400-normal": "https://fonts.gstatic.com/s/hubballi/v10/o-0JIpUj3WIZ1RFN55BmwhF9Yg.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/hubballi/v10/o-0JIpUj3WIZ1RFN55B8whE.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/hubballi/v10/o-0JIpUj3WIZ1RFN55BywhF9Yg.woff2",
  },
} as const;

export type HubballiWeight = "400";
export type HubballiStyle = "normal";
export type HubballiSubset = "kannada" | "latin" | "latin-ext";
export type HubballiOptions = GoogleFontOptions<HubballiWeight, HubballiStyle, HubballiSubset>;

/**
 * Hubballi — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Hubballi extends GoogleFont<HubballiWeight, HubballiStyle, HubballiSubset> {
  constructor(options?: HubballiOptions) {
    super(FAMILY, FACES, options);
  }
}
