// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "IM Fell French Canon SC";

const FACES = {
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/imfellfrenchcanonsc/v23/FBVmdCru5-ifcor2bgq9V89khWcmQghEURY7H0czWhE.woff2",
  },
} as const;

export type IMFellFrenchCanonSCWeight = "400";
export type IMFellFrenchCanonSCStyle = "normal";
export type IMFellFrenchCanonSCSubset = "latin";
export type IMFellFrenchCanonSCOptions = GoogleFontOptions<
  IMFellFrenchCanonSCWeight,
  IMFellFrenchCanonSCStyle,
  IMFellFrenchCanonSCSubset
>;

/**
 * IM Fell French Canon SC — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class IMFellFrenchCanonSC extends GoogleFont<
  IMFellFrenchCanonSCWeight,
  IMFellFrenchCanonSCStyle,
  IMFellFrenchCanonSCSubset
> {
  constructor(options?: IMFellFrenchCanonSCOptions) {
    super(FAMILY, FACES, options);
  }
}
