// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Iosevka Charon";

const FACES = {
  armenian: {
    "300-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYU0uKIsj-gx2.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-re_E7GJk7_g.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xt0e-o8dtuW1FZBLWGprOon7cFafYMPaQC.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xv0e-o8dtuW1FZBLWGprOon7cQWeQUOQ.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYRUvKIsj-gx2.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7_zevE7GJk7_g.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYV0pKIsj-gx2.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-7fPE7GJk7_g.woff2",
  },
  braille: {
    "300-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYU0uKDUC3zFPJA.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-re_GFObwGxzU.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xt0e-o8dtuW1FZBLWGprOon7cFaUgtGJk7_g.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xv0e-o8dtuW1FZBLWGprOon7eueMEpAJ0.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYRUvKDUC3zFPJA.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7_zevGFObwGxzU.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYV0pKDUC3zFPJA.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-7fPGFObwGxzU.woff2",
  },
  cyrillic: {
    "300-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYU0uKJ8j-gx2.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-re_EvGJk7_g.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xt0e-o8dtuW1FZBLWGprOon7cFaeIMPaQC.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xv0e-o8dtuW1FZBLWGprOon7cEWeQUOQ.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYRUvKJ8j-gx2.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7_zevEvGJk7_g.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYV0pKJ8j-gx2.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-7fPEvGJk7_g.woff2",
  },
  "cyrillic-ext": {
    "300-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYU0uKJYj-gx2.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-re_EmGJk7_g.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xt0e-o8dtuW1FZBLWGprOon7cFaesMPaQC.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xv0e-o8dtuW1FZBLWGprOon7cNWeQUOQ.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYRUvKJYj-gx2.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7_zevEmGJk7_g.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYV0pKJYj-gx2.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-7fPEmGJk7_g.woff2",
  },
  greek: {
    "300-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYU0uKJgj-gx2.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-re_EoGJk7_g.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xt0e-o8dtuW1FZBLWGprOon7cFaeUMPaQC.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xv0e-o8dtuW1FZBLWGprOon7cDWeQUOQ.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYRUvKJgj-gx2.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7_zevEoGJk7_g.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYV0pKJgj-gx2.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-7fPEoGJk7_g.woff2",
  },
  "greek-ext": {
    "300-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYU0uKJcj-gx2.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-re_EnGJk7_g.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xt0e-o8dtuW1FZBLWGprOon7cFaeoMPaQC.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xv0e-o8dtuW1FZBLWGprOon7cMWeQUOQ.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYRUvKJcj-gx2.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7_zevEnGJk7_g.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYV0pKJcj-gx2.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-7fPEnGJk7_g.woff2",
  },
  latin: {
    "300-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYU0uKJsj-g.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-re_ErGJk.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xt0e-o8dtuW1FZBLWGprOon7cFaeYMPQ.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xv0e-o8dtuW1FZBLWGprOon7cAWeQ.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYRUvKJsj-g.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7_zevErGJk.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYV0pKJsj-g.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-7fPErGJk.woff2",
  },
  "latin-ext": {
    "300-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYU0uKJUj-gx2.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-re_ElGJk7_g.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xt0e-o8dtuW1FZBLWGprOon7cFaegMPaQC.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xv0e-o8dtuW1FZBLWGprOon7cOWeQUOQ.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYRUvKJUj-gx2.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7_zevElGJk7_g.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYV0pKJUj-gx2.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-7fPElGJk7_g.woff2",
  },
  math: {
    "300-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYU0uKOcj-gx2.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-re_FXGJk7_g.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xt0e-o8dtuW1FZBLWGprOon7cFaZoMPaQC.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xv0e-o8dtuW1FZBLWGprOon7d8WeQUOQ.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYRUvKOcj-gx2.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7_zevFXGJk7_g.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYV0pKOcj-gx2.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-7fPFXGJk7_g.woff2",
  },
  symbols: {
    "300-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYU0uKPUj-gx2.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-re_FFGJk7_g.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xt0e-o8dtuW1FZBLWGprOon7cFaYgMPaQC.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xv0e-o8dtuW1FZBLWGprOon7duWeQUOQ.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYRUvKPUj-gx2.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7_zevFFGJk7_g.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYV0pKPUj-gx2.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-7fPFFGJk7_g.woff2",
  },
  symbols2: {
    "300-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYU0uKCEC3zFPJA.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-re_GRObwGxzU.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xt0e-o8dtuW1FZBLWGprOon7cFaVwtGJk7_g.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xv0e-o8dtuW1FZBLWGprOon7e6eMEpAJ0.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYRUvKCEC3zFPJA.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7_zevGRObwGxzU.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYV0pKCEC3zFPJA.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-7fPGRObwGxzU.woff2",
  },
  vietnamese: {
    "300-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYU0uKJQj-gx2.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-re_EkGJk7_g.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xt0e-o8dtuW1FZBLWGprOon7cFaekMPaQC.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xv0e-o8dtuW1FZBLWGprOon7cPWeQUOQ.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYRUvKJQj-gx2.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7_zevEkGJk7_g.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xq0e-o8dtuW1FZBLWGprOon7cFYV0pKJQj-gx2.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/iosevkacharon/v1/f0Xs0e-o8dtuW1FZBLWGprOon7-7fPEkGJk7_g.woff2",
  },
} as const;

export type IosevkaCharonWeight = "300" | "400" | "500" | "700";
export type IosevkaCharonStyle = "italic" | "normal";
export type IosevkaCharonSubset =
  | "armenian"
  | "braille"
  | "cyrillic"
  | "cyrillic-ext"
  | "greek"
  | "greek-ext"
  | "latin"
  | "latin-ext"
  | "math"
  | "symbols"
  | "symbols2"
  | "vietnamese";
export type IosevkaCharonOptions = GoogleFontOptions<
  IosevkaCharonWeight,
  IosevkaCharonStyle,
  IosevkaCharonSubset
>;

/**
 * Iosevka Charon — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class IosevkaCharon extends GoogleFont<
  IosevkaCharonWeight,
  IosevkaCharonStyle,
  IosevkaCharonSubset
> {
  constructor(options?: IosevkaCharonOptions) {
    super(FAMILY, FACES, options);
  }
}
