// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Jacquarda Bastarda 9";

const FACES = {
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/jacquardabastarda9/v6/f0Xp0fWr_8t6WFtKQJfOhaC0hcZ1HYAMAYwE3zE.woff2",
  },
  "latin-ext": {
    "400-normal":
      "https://fonts.gstatic.com/s/jacquardabastarda9/v6/f0Xp0fWr_8t6WFtKQJfOhaC0hcZ1HYAMAYwK3zFPJA.woff2",
  },
  math: {
    "400-normal":
      "https://fonts.gstatic.com/s/jacquardabastarda9/v6/f0Xp0fWr_8t6WFtKQJfOhaC0hcZ1HYAMAYx43zFPJA.woff2",
  },
  symbols: {
    "400-normal":
      "https://fonts.gstatic.com/s/jacquardabastarda9/v6/f0Xp0fWr_8t6WFtKQJfOhaC0hcZ1HYAMAYxq3zFPJA.woff2",
  },
} as const;

export type JacquardaBastarda9Weight = "400";
export type JacquardaBastarda9Style = "normal";
export type JacquardaBastarda9Subset = "latin" | "latin-ext" | "math" | "symbols";
export type JacquardaBastarda9Options = GoogleFontOptions<
  JacquardaBastarda9Weight,
  JacquardaBastarda9Style,
  JacquardaBastarda9Subset
>;

/**
 * Jacquarda Bastarda 9 — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class JacquardaBastarda9 extends GoogleFont<
  JacquardaBastarda9Weight,
  JacquardaBastarda9Style,
  JacquardaBastarda9Subset
> {
  constructor(options?: JacquardaBastarda9Options) {
    super(FAMILY, FACES, options);
  }
}
