// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Joti One";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/jotione/v28/Z9XVDmdJQAmWm9TwabTZ6Ow.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/jotione/v28/Z9XVDmdJQAmWm9TwabTX6Oy0lw.woff2",
  },
} as const;

export type JotiOneWeight = "400";
export type JotiOneStyle = "normal";
export type JotiOneSubset = "latin" | "latin-ext";
export type JotiOneOptions = GoogleFontOptions<JotiOneWeight, JotiOneStyle, JotiOneSubset>;

/**
 * Joti One — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class JotiOne extends GoogleFont<JotiOneWeight, JotiOneStyle, JotiOneSubset> {
  constructor(options?: JotiOneOptions) {
    super(FAMILY, FACES, options);
  }
}
