// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Just Me Again Down Here";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/justmeagaindownhere/v25/MwQmbgXtz-Wc6RUEGNMc0QpRrfUh2hSdBBMoAtwAtKE.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/justmeagaindownhere/v25/MwQmbgXtz-Wc6RUEGNMc0QpRrfUh2hSdBBMoAtwOtKHAcw.woff2",
  },
} as const;

export type JustMeAgainDownHereWeight = "400";
export type JustMeAgainDownHereStyle = "normal";
export type JustMeAgainDownHereSubset = "latin" | "latin-ext";
export type JustMeAgainDownHereOptions = GoogleFontOptions<JustMeAgainDownHereWeight, JustMeAgainDownHereStyle, JustMeAgainDownHereSubset>;

/**
 * Just Me Again Down Here — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class JustMeAgainDownHere extends GoogleFont<JustMeAgainDownHereWeight, JustMeAgainDownHereStyle, JustMeAgainDownHereSubset> {
  constructor(options?: JustMeAgainDownHereOptions) {
    super(FAMILY, FACES, options);
  }
}
