// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Kaisei Tokumin";

const FACES = {
  "cyrillic": {
    "400-normal": "https://fonts.gstatic.com/s/kaiseitokumin/v11/Gg8sN5wdZg7xCwuMsylww2ZiQnJc3FwZjw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/kaiseitokumin/v11/Gg8vN5wdZg7xCwuMsylww2ZiQnqr_0kirsMDeA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/kaiseitokumin/v11/Gg8vN5wdZg7xCwuMsylww2ZiQnrj-UkirsMDeA.woff2",
    "800-normal": "https://fonts.gstatic.com/s/kaiseitokumin/v11/Gg8vN5wdZg7xCwuMsylww2ZiQnr_-kkirsMDeA.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/kaiseitokumin/v11/Gg8sN5wdZg7xCwuMsylww2ZiQnJY3Fw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/kaiseitokumin/v11/Gg8vN5wdZg7xCwuMsylww2ZiQnqr_0kmrsM.woff2",
    "700-normal": "https://fonts.gstatic.com/s/kaiseitokumin/v11/Gg8vN5wdZg7xCwuMsylww2ZiQnrj-UkmrsM.woff2",
    "800-normal": "https://fonts.gstatic.com/s/kaiseitokumin/v11/Gg8vN5wdZg7xCwuMsylww2ZiQnr_-kkmrsM.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/kaiseitokumin/v11/Gg8sN5wdZg7xCwuMsylww2ZiQnJW3FwZjw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/kaiseitokumin/v11/Gg8vN5wdZg7xCwuMsylww2ZiQnqr_0korsMDeA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/kaiseitokumin/v11/Gg8vN5wdZg7xCwuMsylww2ZiQnrj-UkorsMDeA.woff2",
    "800-normal": "https://fonts.gstatic.com/s/kaiseitokumin/v11/Gg8vN5wdZg7xCwuMsylww2ZiQnr_-kkorsMDeA.woff2",
  },
} as const;

export type KaiseiTokuminWeight = "400" | "500" | "700" | "800";
export type KaiseiTokuminStyle = "normal";
export type KaiseiTokuminSubset = "cyrillic" | "latin" | "latin-ext";
export type KaiseiTokuminOptions = GoogleFontOptions<KaiseiTokuminWeight, KaiseiTokuminStyle, KaiseiTokuminSubset>;

/**
 * Kaisei Tokumin — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class KaiseiTokumin extends GoogleFont<KaiseiTokuminWeight, KaiseiTokuminStyle, KaiseiTokuminSubset> {
  constructor(options?: KaiseiTokuminOptions) {
    super(FAMILY, FACES, options);
  }
}
