// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Karma";

const FACES = {
  devanagari: {
    "300-normal": "https://fonts.gstatic.com/s/karma/v18/va9F4kzAzMZRGLjDY_Z5sK32QA.woff2",
    "400-normal": "https://fonts.gstatic.com/s/karma/v18/va9I4kzAzMZRGLBpQeNHkQ.woff2",
    "500-normal": "https://fonts.gstatic.com/s/karma/v18/va9F4kzAzMZRGLibYvZ5sK32QA.woff2",
    "600-normal": "https://fonts.gstatic.com/s/karma/v18/va9F4kzAzMZRGLi3ZfZ5sK32QA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/karma/v18/va9F4kzAzMZRGLjTZPZ5sK32QA.woff2",
  },
  latin: {
    "300-normal": "https://fonts.gstatic.com/s/karma/v18/va9F4kzAzMZRGLjDY_Z4sK0.woff2",
    "400-normal": "https://fonts.gstatic.com/s/karma/v18/va9I4kzAzMZRGLBoQeM.woff2",
    "500-normal": "https://fonts.gstatic.com/s/karma/v18/va9F4kzAzMZRGLibYvZ4sK0.woff2",
    "600-normal": "https://fonts.gstatic.com/s/karma/v18/va9F4kzAzMZRGLi3ZfZ4sK0.woff2",
    "700-normal": "https://fonts.gstatic.com/s/karma/v18/va9F4kzAzMZRGLjTZPZ4sK0.woff2",
  },
  "latin-ext": {
    "300-normal": "https://fonts.gstatic.com/s/karma/v18/va9F4kzAzMZRGLjDY_Z2sK32QA.woff2",
    "400-normal": "https://fonts.gstatic.com/s/karma/v18/va9I4kzAzMZRGLBmQeNHkQ.woff2",
    "500-normal": "https://fonts.gstatic.com/s/karma/v18/va9F4kzAzMZRGLibYvZ2sK32QA.woff2",
    "600-normal": "https://fonts.gstatic.com/s/karma/v18/va9F4kzAzMZRGLi3ZfZ2sK32QA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/karma/v18/va9F4kzAzMZRGLjTZPZ2sK32QA.woff2",
  },
} as const;

export type KarmaWeight = "300" | "400" | "500" | "600" | "700";
export type KarmaStyle = "normal";
export type KarmaSubset = "devanagari" | "latin" | "latin-ext";
export type KarmaOptions = GoogleFontOptions<KarmaWeight, KarmaStyle, KarmaSubset>;

/**
 * Karma — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Karma extends GoogleFont<KarmaWeight, KarmaStyle, KarmaSubset> {
  constructor(options?: KarmaOptions) {
    super(FAMILY, FACES, options);
  }
}
