// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Katibeh";

const FACES = {
  arabic: {
    "400-normal": "https://fonts.gstatic.com/s/katibeh/v22/ZGjXol5MQJog4bxDWC9bVQNd.woff2",
  },
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/katibeh/v22/ZGjXol5MQJog4bxDWCpbVQ.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/katibeh/v22/ZGjXol5MQJog4bxDWCRbVQNd.woff2",
  },
} as const;

export type KatibehWeight = "400";
export type KatibehStyle = "normal";
export type KatibehSubset = "arabic" | "latin" | "latin-ext";
export type KatibehOptions = GoogleFontOptions<KatibehWeight, KatibehStyle, KatibehSubset>;

/**
 * Katibeh — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Katibeh extends GoogleFont<KatibehWeight, KatibehStyle, KatibehSubset> {
  constructor(options?: KatibehOptions) {
    super(FAMILY, FACES, options);
  }
}
