// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Kavoon";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/kavoon/v25/pxiFyp4_scRYhlUIM7D7.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/kavoon/v25/pxiFyp4_scRYhlUIPbD7T1o.woff2",
  },
} as const;

export type KavoonWeight = "400";
export type KavoonStyle = "normal";
export type KavoonSubset = "latin" | "latin-ext";
export type KavoonOptions = GoogleFontOptions<KavoonWeight, KavoonStyle, KavoonSubset>;

/**
 * Kavoon — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Kavoon extends GoogleFont<KavoonWeight, KavoonStyle, KavoonSubset> {
  constructor(options?: KavoonOptions) {
    super(FAMILY, FACES, options);
  }
}
