// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Kelly Slab";

const FACES = {
  "cyrillic": {
    "400-normal": "https://fonts.gstatic.com/s/kellyslab/v18/-W_7XJX0Rz3cxUnJC5t6fkALfq0k.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/kellyslab/v18/-W_7XJX0Rz3cxUnJC5t6fkQLfg.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/kellyslab/v18/-W_7XJX0Rz3cxUnJC5t6fkoLfq0k.woff2",
  },
} as const;

export type KellySlabWeight = "400";
export type KellySlabStyle = "normal";
export type KellySlabSubset = "cyrillic" | "latin" | "latin-ext";
export type KellySlabOptions = GoogleFontOptions<KellySlabWeight, KellySlabStyle, KellySlabSubset>;

/**
 * Kelly Slab — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class KellySlab extends GoogleFont<KellySlabWeight, KellySlabStyle, KellySlabSubset> {
  constructor(options?: KellySlabOptions) {
    super(FAMILY, FACES, options);
  }
}
