// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Koulen";

const FACES = {
  "khmer": {
    "400-normal": "https://fonts.gstatic.com/s/koulen/v30/AMOQz46as3KIBPemjno8ouY.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/koulen/v30/AMOQz46as3KIBPemhXo8.woff2",
  },
} as const;

export type KoulenWeight = "400";
export type KoulenStyle = "normal";
export type KoulenSubset = "khmer" | "latin";
export type KoulenOptions = GoogleFontOptions<KoulenWeight, KoulenStyle, KoulenSubset>;

/**
 * Koulen — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Koulen extends GoogleFont<KoulenWeight, KoulenStyle, KoulenSubset> {
  constructor(options?: KoulenOptions) {
    super(FAMILY, FACES, options);
  }
}
