// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Libre Barcode 39";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/librebarcode39/v25/-nFnOHM08vwC6h8Li1eQnP_AHzI2G_Bx0g.woff2",
  },
} as const;

export type LibreBarcode39Weight = "400";
export type LibreBarcode39Style = "normal";
export type LibreBarcode39Subset = "latin";
export type LibreBarcode39Options = GoogleFontOptions<LibreBarcode39Weight, LibreBarcode39Style, LibreBarcode39Subset>;

/**
 * Libre Barcode 39 — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class LibreBarcode39 extends GoogleFont<LibreBarcode39Weight, LibreBarcode39Style, LibreBarcode39Subset> {
  constructor(options?: LibreBarcode39Options) {
    super(FAMILY, FACES, options);
  }
}
