// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Lilita One";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/lilitaone/v17/i7dPIFZ9Zz-WBtRtedDbYEF8RQ.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/lilitaone/v17/i7dPIFZ9Zz-WBtRtedDbYE98RWq7.woff2",
  },
} as const;

export type LilitaOneWeight = "400";
export type LilitaOneStyle = "normal";
export type LilitaOneSubset = "latin" | "latin-ext";
export type LilitaOneOptions = GoogleFontOptions<LilitaOneWeight, LilitaOneStyle, LilitaOneSubset>;

/**
 * Lilita One — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class LilitaOne extends GoogleFont<LilitaOneWeight, LilitaOneStyle, LilitaOneSubset> {
  constructor(options?: LilitaOneOptions) {
    super(FAMILY, FACES, options);
  }
}
