// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Lovers Quarrel";

const FACES = {
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/loversquarrel/v25/Yq6N-LSKXTL-5bCy8ksBzpQ_-wArabs.woff2",
  },
  "latin-ext": {
    "400-normal":
      "https://fonts.gstatic.com/s/loversquarrel/v25/Yq6N-LSKXTL-5bCy8ksBzpQ_-wAlabt-6g.woff2",
  },
  vietnamese: {
    "400-normal":
      "https://fonts.gstatic.com/s/loversquarrel/v25/Yq6N-LSKXTL-5bCy8ksBzpQ_-wAkabt-6g.woff2",
  },
} as const;

export type LoversQuarrelWeight = "400";
export type LoversQuarrelStyle = "normal";
export type LoversQuarrelSubset = "latin" | "latin-ext" | "vietnamese";
export type LoversQuarrelOptions = GoogleFontOptions<
  LoversQuarrelWeight,
  LoversQuarrelStyle,
  LoversQuarrelSubset
>;

/**
 * Lovers Quarrel — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class LoversQuarrel extends GoogleFont<
  LoversQuarrelWeight,
  LoversQuarrelStyle,
  LoversQuarrelSubset
> {
  constructor(options?: LoversQuarrelOptions) {
    super(FAMILY, FACES, options);
  }
}
