// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Lunasima";

const FACES = {
  cyrillic: {
    "400-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO-EBvPh9RSOj7JFDwmcd831Q.woff2",
    "700-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO5EBvPh9RSOj7JFDSZVMoM9E8niA.woff2",
  },
  "cyrillic-ext": {
    "400-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO-EBvPh9RSOj7JFDwvcd831Q.woff2",
    "700-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO5EBvPh9RSOj7JFDSZVMoF9E8niA.woff2",
  },
  greek: {
    "400-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO-EBvPh9RSOj7JFDwhcd831Q.woff2",
    "700-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO5EBvPh9RSOj7JFDSZVMoL9E8niA.woff2",
  },
  "greek-ext": {
    "400-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO-EBvPh9RSOj7JFDwucd831Q.woff2",
    "700-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO5EBvPh9RSOj7JFDSZVMoE9E8niA.woff2",
  },
  hebrew: {
    "400-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO-EBvPh9RSOj7JFDwgcd831Q.woff2",
    "700-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO5EBvPh9RSOj7JFDSZVMoK9E8niA.woff2",
  },
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO-EBvPh9RSOj7JFDwicd8.woff2",
    "700-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO5EBvPh9RSOj7JFDSZVMoI9E8.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO-EBvPh9RSOj7JFDwscd831Q.woff2",
    "700-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO5EBvPh9RSOj7JFDSZVMoG9E8niA.woff2",
  },
  vietnamese: {
    "400-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO-EBvPh9RSOj7JFDwtcd831Q.woff2",
    "700-normal": "https://fonts.gstatic.com/s/lunasima/v1/wEO5EBvPh9RSOj7JFDSZVMoH9E8niA.woff2",
  },
} as const;

export type LunasimaWeight = "400" | "700";
export type LunasimaStyle = "normal";
export type LunasimaSubset =
  | "cyrillic"
  | "cyrillic-ext"
  | "greek"
  | "greek-ext"
  | "hebrew"
  | "latin"
  | "latin-ext"
  | "vietnamese";
export type LunasimaOptions = GoogleFontOptions<LunasimaWeight, LunasimaStyle, LunasimaSubset>;

/**
 * Lunasima — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Lunasima extends GoogleFont<LunasimaWeight, LunasimaStyle, LunasimaSubset> {
  constructor(options?: LunasimaOptions) {
    super(FAMILY, FACES, options);
  }
}
