// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Lustria";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/lustria/v14/9oRONYodvDEyjuhOnC8zMw.woff2",
  },
} as const;

export type LustriaWeight = "400";
export type LustriaStyle = "normal";
export type LustriaSubset = "latin";
export type LustriaOptions = GoogleFontOptions<LustriaWeight, LustriaStyle, LustriaSubset>;

/**
 * Lustria — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Lustria extends GoogleFont<LustriaWeight, LustriaStyle, LustriaSubset> {
  constructor(options?: LustriaOptions) {
    super(FAMILY, FACES, options);
  }
}
