// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Mansalva";

const FACES = {
  "greek": {
    "400-normal": "https://fonts.gstatic.com/s/mansalva/v16/aWB4m0aacbtDfvq5NKlhKY_fdw.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/mansalva/v16/aWB4m0aacbtDfvq5NKliKY8.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/mansalva/v16/aWB4m0aacbtDfvq5NKlsKY_fdw.woff2",
  },
  "vietnamese": {
    "400-normal": "https://fonts.gstatic.com/s/mansalva/v16/aWB4m0aacbtDfvq5NKltKY_fdw.woff2",
  },
} as const;

export type MansalvaWeight = "400";
export type MansalvaStyle = "normal";
export type MansalvaSubset = "greek" | "latin" | "latin-ext" | "vietnamese";
export type MansalvaOptions = GoogleFontOptions<MansalvaWeight, MansalvaStyle, MansalvaSubset>;

/**
 * Mansalva — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Mansalva extends GoogleFont<MansalvaWeight, MansalvaStyle, MansalvaSubset> {
  constructor(options?: MansalvaOptions) {
    super(FAMILY, FACES, options);
  }
}
