// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Margarine";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/margarine/v27/qkBXXvoE6trLT9Y7YLyu455K.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/margarine/v27/qkBXXvoE6trLT9Y7YLyu7Z5KoAU.woff2",
  },
} as const;

export type MargarineWeight = "400";
export type MargarineStyle = "normal";
export type MargarineSubset = "latin" | "latin-ext";
export type MargarineOptions = GoogleFontOptions<MargarineWeight, MargarineStyle, MargarineSubset>;

/**
 * Margarine — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Margarine extends GoogleFont<MargarineWeight, MargarineStyle, MargarineSubset> {
  constructor(options?: MargarineOptions) {
    super(FAMILY, FACES, options);
  }
}
