// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Marvel";

const FACES = {
  latin: {
    "400-italic": "https://fonts.gstatic.com/s/marvel/v17/nwpXtKeoNgBV0qa4k2THJ3o.woff2",
    "400-normal": "https://fonts.gstatic.com/s/marvel/v17/nwpVtKeoNgBV0qa4llTF.woff2",
    "700-italic": "https://fonts.gstatic.com/s/marvel/v17/nwpQtKeoNgBV0qa4k2x8Am-l7w0.woff2",
    "700-normal": "https://fonts.gstatic.com/s/marvel/v17/nwpWtKeoNgBV0qawLXHQAF-n.woff2",
  },
} as const;

export type MarvelWeight = "400" | "700";
export type MarvelStyle = "italic" | "normal";
export type MarvelSubset = "latin";
export type MarvelOptions = GoogleFontOptions<MarvelWeight, MarvelStyle, MarvelSubset>;

/**
 * Marvel — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Marvel extends GoogleFont<MarvelWeight, MarvelStyle, MarvelSubset> {
  constructor(options?: MarvelOptions) {
    super(FAMILY, FACES, options);
  }
}
