// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Mate";

const FACES = {
  latin: {
    "400-italic": "https://fonts.gstatic.com/s/mate/v19/m8JTjftRd7WZ6z-GWa3W.woff2",
    "400-normal": "https://fonts.gstatic.com/s/mate/v19/m8JdjftRd7WZ6zq2Ww.woff2",
  },
  "latin-ext": {
    "400-italic": "https://fonts.gstatic.com/s/mate/v19/m8JTjftRd7WZ6z-GV63WSLU.woff2",
    "400-normal": "https://fonts.gstatic.com/s/mate/v19/m8JdjftRd7WZ6zS2W7XS.woff2",
  },
} as const;

export type MateWeight = "400";
export type MateStyle = "italic" | "normal";
export type MateSubset = "latin" | "latin-ext";
export type MateOptions = GoogleFontOptions<MateWeight, MateStyle, MateSubset>;

/**
 * Mate — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Mate extends GoogleFont<MateWeight, MateStyle, MateSubset> {
  constructor(options?: MateOptions) {
    super(FAMILY, FACES, options);
  }
}
