// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Metal";

const FACES = {
  "khmer": {
    "400-normal": "https://fonts.gstatic.com/s/metal/v32/lW-wwjUJIXTo7h3rlIUwUQ.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/metal/v32/lW-wwjUJIXTo7h3glIU.woff2",
  },
} as const;

export type MetalWeight = "400";
export type MetalStyle = "normal";
export type MetalSubset = "khmer" | "latin";
export type MetalOptions = GoogleFontOptions<MetalWeight, MetalStyle, MetalSubset>;

/**
 * Metal — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Metal extends GoogleFont<MetalWeight, MetalStyle, MetalSubset> {
  constructor(options?: MetalOptions) {
    super(FAMILY, FACES, options);
  }
}
