// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Milonga";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/milonga/v24/SZc53FHnIaK9W5kfTzrMkA.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/milonga/v24/SZc53FHnIaK9W5kfTzTMkHrS.woff2",
  },
} as const;

export type MilongaWeight = "400";
export type MilongaStyle = "normal";
export type MilongaSubset = "latin" | "latin-ext";
export type MilongaOptions = GoogleFontOptions<MilongaWeight, MilongaStyle, MilongaSubset>;

/**
 * Milonga — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Milonga extends GoogleFont<MilongaWeight, MilongaStyle, MilongaSubset> {
  constructor(options?: MilongaOptions) {
    super(FAMILY, FACES, options);
  }
}
