// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Miniver";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/miniver/v27/eLGcP-PxIg-5H0vC37oIyg.woff2",
  },
} as const;

export type MiniverWeight = "400";
export type MiniverStyle = "normal";
export type MiniverSubset = "latin";
export type MiniverOptions = GoogleFontOptions<MiniverWeight, MiniverStyle, MiniverSubset>;

/**
 * Miniver — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Miniver extends GoogleFont<MiniverWeight, MiniverStyle, MiniverSubset> {
  constructor(options?: MiniverOptions) {
    super(FAMILY, FACES, options);
  }
}
