// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Miranda Sans";

const FACES = {
  "latin": {
    "400-italic": "https://fonts.gstatic.com/s/mirandasans/v3/aFTN7Pt8ZWk4XsiWhk7Rb_edar37fl0.woff2",
    "400-normal": "https://fonts.gstatic.com/s/mirandasans/v3/aFTT7Pt8ZWk4XsiWhk7Rb_edb435.woff2",
    "500-italic": "https://fonts.gstatic.com/s/mirandasans/v3/aFTN7Pt8ZWk4XsiWhk7Rb_edar37fl0.woff2",
    "500-normal": "https://fonts.gstatic.com/s/mirandasans/v3/aFTT7Pt8ZWk4XsiWhk7Rb_edb435.woff2",
    "600-italic": "https://fonts.gstatic.com/s/mirandasans/v3/aFTN7Pt8ZWk4XsiWhk7Rb_edar37fl0.woff2",
    "600-normal": "https://fonts.gstatic.com/s/mirandasans/v3/aFTT7Pt8ZWk4XsiWhk7Rb_edb435.woff2",
    "700-italic": "https://fonts.gstatic.com/s/mirandasans/v3/aFTN7Pt8ZWk4XsiWhk7Rb_edar37fl0.woff2",
    "700-normal": "https://fonts.gstatic.com/s/mirandasans/v3/aFTT7Pt8ZWk4XsiWhk7Rb_edb435.woff2",
  },
  "latin-ext": {
    "400-italic": "https://fonts.gstatic.com/s/mirandasans/v3/aFTN7Pt8ZWk4XsiWhk7Rb_edar31fl13uA.woff2",
    "400-normal": "https://fonts.gstatic.com/s/mirandasans/v3/aFTT7Pt8ZWk4XsiWhk7Rb_edYY35Zlk.woff2",
    "500-italic": "https://fonts.gstatic.com/s/mirandasans/v3/aFTN7Pt8ZWk4XsiWhk7Rb_edar31fl13uA.woff2",
    "500-normal": "https://fonts.gstatic.com/s/mirandasans/v3/aFTT7Pt8ZWk4XsiWhk7Rb_edYY35Zlk.woff2",
    "600-italic": "https://fonts.gstatic.com/s/mirandasans/v3/aFTN7Pt8ZWk4XsiWhk7Rb_edar31fl13uA.woff2",
    "600-normal": "https://fonts.gstatic.com/s/mirandasans/v3/aFTT7Pt8ZWk4XsiWhk7Rb_edYY35Zlk.woff2",
    "700-italic": "https://fonts.gstatic.com/s/mirandasans/v3/aFTN7Pt8ZWk4XsiWhk7Rb_edar31fl13uA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/mirandasans/v3/aFTT7Pt8ZWk4XsiWhk7Rb_edYY35Zlk.woff2",
  },
} as const;

export type MirandaSansWeight = "400" | "500" | "600" | "700";
export type MirandaSansStyle = "italic" | "normal";
export type MirandaSansSubset = "latin" | "latin-ext";
export type MirandaSansOptions = GoogleFontOptions<MirandaSansWeight, MirandaSansStyle, MirandaSansSubset>;

/**
 * Miranda Sans — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class MirandaSans extends GoogleFont<MirandaSansWeight, MirandaSansStyle, MirandaSansSubset> {
  constructor(options?: MirandaSansOptions) {
    super(FAMILY, FACES, options);
  }
}
