// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Momo Signature";

const FACES = {
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/momosignature/v2/RrQJbop99C51b06IDAuFoM0yCpcvO8g.woff2",
  },
  "latin-ext": {
    "400-normal":
      "https://fonts.gstatic.com/s/momosignature/v2/RrQJbop99C51b06IDAuFoM0yCpchO8i5PA.woff2",
  },
  vietnamese: {
    "400-normal":
      "https://fonts.gstatic.com/s/momosignature/v2/RrQJbop99C51b06IDAuFoM0yCpcgO8i5PA.woff2",
  },
} as const;

export type MomoSignatureWeight = "400";
export type MomoSignatureStyle = "normal";
export type MomoSignatureSubset = "latin" | "latin-ext" | "vietnamese";
export type MomoSignatureOptions = GoogleFontOptions<
  MomoSignatureWeight,
  MomoSignatureStyle,
  MomoSignatureSubset
>;

/**
 * Momo Signature — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class MomoSignature extends GoogleFont<
  MomoSignatureWeight,
  MomoSignatureStyle,
  MomoSignatureSubset
> {
  constructor(options?: MomoSignatureOptions) {
    super(FAMILY, FACES, options);
  }
}
