// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Montagu Slab";

const FACES = {
  "latin": {
    "100-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5xGLdw.woff2",
    "200-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5xGLdw.woff2",
    "300-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5xGLdw.woff2",
    "400-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5xGLdw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5xGLdw.woff2",
    "600-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5xGLdw.woff2",
    "700-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5xGLdw.woff2",
  },
  "latin-ext": {
    "100-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x-Ld6d7.woff2",
    "200-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x-Ld6d7.woff2",
    "300-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x-Ld6d7.woff2",
    "400-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x-Ld6d7.woff2",
    "500-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x-Ld6d7.woff2",
    "600-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x-Ld6d7.woff2",
    "700-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x-Ld6d7.woff2",
  },
  "vietnamese": {
    "100-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x6Ld6d7.woff2",
    "200-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x6Ld6d7.woff2",
    "300-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x6Ld6d7.woff2",
    "400-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x6Ld6d7.woff2",
    "500-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x6Ld6d7.woff2",
    "600-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x6Ld6d7.woff2",
    "700-normal": "https://fonts.gstatic.com/s/montaguslab/v17/6qLSKZIQtB_zv0xUaXRDWkY_HXsphdLRZF40vm_j5x6Ld6d7.woff2",
  },
} as const;

export type MontaguSlabWeight = "100" | "200" | "300" | "400" | "500" | "600" | "700";
export type MontaguSlabStyle = "normal";
export type MontaguSlabSubset = "latin" | "latin-ext" | "vietnamese";
export type MontaguSlabOptions = GoogleFontOptions<MontaguSlabWeight, MontaguSlabStyle, MontaguSlabSubset>;

/**
 * Montagu Slab — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class MontaguSlab extends GoogleFont<MontaguSlabWeight, MontaguSlabStyle, MontaguSlabSubset> {
  constructor(options?: MontaguSlabOptions) {
    super(FAMILY, FACES, options);
  }
}
