// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Mooli";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/mooli/v1/-F6_fjJpLyk1bbPGDm8.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/mooli/v1/-F6_fjJpLyk1bbPIDm_opw.woff2",
  },
} as const;

export type MooliWeight = "400";
export type MooliStyle = "normal";
export type MooliSubset = "latin" | "latin-ext";
export type MooliOptions = GoogleFontOptions<MooliWeight, MooliStyle, MooliSubset>;

/**
 * Mooli — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Mooli extends GoogleFont<MooliWeight, MooliStyle, MooliSubset> {
  constructor(options?: MooliOptions) {
    super(FAMILY, FACES, options);
  }
}
