// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Mukta Malar";

const FACES = {
  "latin": {
    "200-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqIMwBuAG4Ws.woff2",
    "300-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqINUBeAG4Ws.woff2",
    "400-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoXzAXyz8LOE2FpJMxZqIv_J_U.woff2",
    "500-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqIMMBOAG4Ws.woff2",
    "600-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqIMgA-AG4Ws.woff2",
    "700-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqINEAuAG4Ws.woff2",
    "800-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqINYAeAG4Ws.woff2",
  },
  "latin-ext": {
    "200-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqIMwBuAI4WveoA.woff2",
    "300-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqINUBeAI4WveoA.woff2",
    "400-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoXzAXyz8LOE2FpJMxZqIvxJ_U5wA.woff2",
    "500-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqIMMBOAI4WveoA.woff2",
    "600-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqIMgA-AI4WveoA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqINEAuAI4WveoA.woff2",
    "800-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqINYAeAI4WveoA.woff2",
  },
  "tamil": {
    "200-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqIMwBuAQ4WveoA.woff2",
    "300-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqINUBeAQ4WveoA.woff2",
    "400-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoXzAXyz8LOE2FpJMxZqIvpJ_U5wA.woff2",
    "500-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqIMMBOAQ4WveoA.woff2",
    "600-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqIMgA-AQ4WveoA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqINEAuAQ4WveoA.woff2",
    "800-normal": "https://fonts.gstatic.com/s/muktamalar/v14/MCoKzAXyz8LOE2FpJMxZqINYAeAQ4WveoA.woff2",
  },
} as const;

export type MuktaMalarWeight = "200" | "300" | "400" | "500" | "600" | "700" | "800";
export type MuktaMalarStyle = "normal";
export type MuktaMalarSubset = "latin" | "latin-ext" | "tamil";
export type MuktaMalarOptions = GoogleFontOptions<MuktaMalarWeight, MuktaMalarStyle, MuktaMalarSubset>;

/**
 * Mukta Malar — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class MuktaMalar extends GoogleFont<MuktaMalarWeight, MuktaMalarStyle, MuktaMalarSubset> {
  constructor(options?: MuktaMalarOptions) {
    super(FAMILY, FACES, options);
  }
}
