// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Nothing You Could Do";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/nothingyoucoulddo/v21/oY1B8fbBpaP5OX3DtrRYf_Q2BPB1SnfZb3OOnVs.woff2",
  },
} as const;

export type NothingYouCouldDoWeight = "400";
export type NothingYouCouldDoStyle = "normal";
export type NothingYouCouldDoSubset = "latin";
export type NothingYouCouldDoOptions = GoogleFontOptions<NothingYouCouldDoWeight, NothingYouCouldDoStyle, NothingYouCouldDoSubset>;

/**
 * Nothing You Could Do — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class NothingYouCouldDo extends GoogleFont<NothingYouCouldDoWeight, NothingYouCouldDoStyle, NothingYouCouldDoSubset> {
  constructor(options?: NothingYouCouldDoOptions) {
    super(FAMILY, FACES, options);
  }
}
