// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Noto Sans Lepcha";

const FACES = {
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/notosanslepcha/v20/0QI7MWlB_JWgA166SKhu05TekNS36AVmtw.woff2",
  },
  "latin-ext": {
    "400-normal":
      "https://fonts.gstatic.com/s/notosanslepcha/v20/0QI7MWlB_JWgA166SKhu05TekNS36Atmt5BX.woff2",
  },
  lepcha: {
    "400-normal":
      "https://fonts.gstatic.com/s/notosanslepcha/v20/0QI7MWlB_JWgA166SKhu05TekNS36D1mt5BX.woff2",
  },
} as const;

export type NotoSansLepchaWeight = "400";
export type NotoSansLepchaStyle = "normal";
export type NotoSansLepchaSubset = "latin" | "latin-ext" | "lepcha";
export type NotoSansLepchaOptions = GoogleFontOptions<
  NotoSansLepchaWeight,
  NotoSansLepchaStyle,
  NotoSansLepchaSubset
>;

/**
 * Noto Sans Lepcha — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class NotoSansLepcha extends GoogleFont<
  NotoSansLepchaWeight,
  NotoSansLepchaStyle,
  NotoSansLepchaSubset
> {
  constructor(options?: NotoSansLepchaOptions) {
    super(FAMILY, FACES, options);
  }
}
