// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Noto Sans Brahmi";

const FACES = {
  brahmi: {
    "400-normal":
      "https://fonts.gstatic.com/s/notosansbrahmi/v20/vEFK2-VODB8RrNDvZSUmQQIIByV1woS_Wo7H.woff2",
  },
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/notosansbrahmi/v20/vEFK2-VODB8RrNDvZSUmQQIIByV1wtW_Wg.woff2",
  },
  "latin-ext": {
    "400-normal":
      "https://fonts.gstatic.com/s/notosansbrahmi/v20/vEFK2-VODB8RrNDvZSUmQQIIByV1wtu_Wo7H.woff2",
  },
  math: {
    "400-normal":
      "https://fonts.gstatic.com/s/notosansbrahmi/v20/vEFK2-VODB8RrNDvZSUmQQIIByV1wqm_Wo7H.woff2",
  },
  symbols: {
    "400-normal":
      "https://fonts.gstatic.com/s/notosansbrahmi/v20/vEFK2-VODB8RrNDvZSUmQQIIByV1wru_Wo7H.woff2",
  },
} as const;

export type NotoSansBrahmiWeight = "400";
export type NotoSansBrahmiStyle = "normal";
export type NotoSansBrahmiSubset = "brahmi" | "latin" | "latin-ext" | "math" | "symbols";
export type NotoSansBrahmiOptions = GoogleFontOptions<
  NotoSansBrahmiWeight,
  NotoSansBrahmiStyle,
  NotoSansBrahmiSubset
>;

/**
 * Noto Sans Brahmi — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class NotoSansBrahmi extends GoogleFont<
  NotoSansBrahmiWeight,
  NotoSansBrahmiStyle,
  NotoSansBrahmiSubset
> {
  constructor(options?: NotoSansBrahmiOptions) {
    super(FAMILY, FACES, options);
  }
}
