// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Noto Sans Medefaidrin";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/notosansmedefaidrin/v29/WwkAxOq6Dk-wranENynkfeVsNbRZtbOIdLbfdz99.woff2",
    "500-normal": "https://fonts.gstatic.com/s/notosansmedefaidrin/v29/WwkAxOq6Dk-wranENynkfeVsNbRZtbOIdLbfdz99.woff2",
    "600-normal": "https://fonts.gstatic.com/s/notosansmedefaidrin/v29/WwkAxOq6Dk-wranENynkfeVsNbRZtbOIdLbfdz99.woff2",
    "700-normal": "https://fonts.gstatic.com/s/notosansmedefaidrin/v29/WwkAxOq6Dk-wranENynkfeVsNbRZtbOIdLbfdz99.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/notosansmedefaidrin/v29/WwkAxOq6Dk-wranENynkfeVsNbRZtbOIdLbfeT99CQs.woff2",
    "500-normal": "https://fonts.gstatic.com/s/notosansmedefaidrin/v29/WwkAxOq6Dk-wranENynkfeVsNbRZtbOIdLbfeT99CQs.woff2",
    "600-normal": "https://fonts.gstatic.com/s/notosansmedefaidrin/v29/WwkAxOq6Dk-wranENynkfeVsNbRZtbOIdLbfeT99CQs.woff2",
    "700-normal": "https://fonts.gstatic.com/s/notosansmedefaidrin/v29/WwkAxOq6Dk-wranENynkfeVsNbRZtbOIdLbfeT99CQs.woff2",
  },
  "medefaidrin": {
    "400-normal": "https://fonts.gstatic.com/s/notosansmedefaidrin/v29/WwkAxOq6Dk-wranENynkfeVsNbRZtbOIdLbf5h5YNDIU.woff2",
    "500-normal": "https://fonts.gstatic.com/s/notosansmedefaidrin/v29/WwkAxOq6Dk-wranENynkfeVsNbRZtbOIdLbf5h5YNDIU.woff2",
    "600-normal": "https://fonts.gstatic.com/s/notosansmedefaidrin/v29/WwkAxOq6Dk-wranENynkfeVsNbRZtbOIdLbf5h5YNDIU.woff2",
    "700-normal": "https://fonts.gstatic.com/s/notosansmedefaidrin/v29/WwkAxOq6Dk-wranENynkfeVsNbRZtbOIdLbf5h5YNDIU.woff2",
  },
} as const;

export type NotoSansMedefaidrinWeight = "400" | "500" | "600" | "700";
export type NotoSansMedefaidrinStyle = "normal";
export type NotoSansMedefaidrinSubset = "latin" | "latin-ext" | "medefaidrin";
export type NotoSansMedefaidrinOptions = GoogleFontOptions<NotoSansMedefaidrinWeight, NotoSansMedefaidrinStyle, NotoSansMedefaidrinSubset>;

/**
 * Noto Sans Medefaidrin — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class NotoSansMedefaidrin extends GoogleFont<NotoSansMedefaidrinWeight, NotoSansMedefaidrinStyle, NotoSansMedefaidrinSubset> {
  constructor(options?: NotoSansMedefaidrinOptions) {
    super(FAMILY, FACES, options);
  }
}
