// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Noto Sans Oriya";

const FACES = {
  "latin": {
    "100-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjK71A.woff2",
    "200-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjK71A.woff2",
    "300-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjK71A.woff2",
    "400-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjK71A.woff2",
    "500-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjK71A.woff2",
    "600-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjK71A.woff2",
    "700-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjK71A.woff2",
    "800-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjK71A.woff2",
    "900-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjK71A.woff2",
  },
  "latin-ext": {
    "100-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjy71Owo.woff2",
    "200-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjy71Owo.woff2",
    "300-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjy71Owo.woff2",
    "400-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjy71Owo.woff2",
    "500-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjy71Owo.woff2",
    "600-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjy71Owo.woff2",
    "700-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjy71Owo.woff2",
    "800-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjy71Owo.woff2",
    "900-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqjy71Owo.woff2",
  },
  "oriya": {
    "100-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqiu71Owo.woff2",
    "200-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqiu71Owo.woff2",
    "300-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqiu71Owo.woff2",
    "400-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqiu71Owo.woff2",
    "500-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqiu71Owo.woff2",
    "600-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqiu71Owo.woff2",
    "700-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqiu71Owo.woff2",
    "800-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqiu71Owo.woff2",
    "900-normal": "https://fonts.gstatic.com/s/notosansoriya/v35/AYCcpXfzfccDCstK_hrjDyADv5e9748vhj3CJBLHIARtqiu71Owo.woff2",
  },
} as const;

export type NotoSansOriyaWeight = "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900";
export type NotoSansOriyaStyle = "normal";
export type NotoSansOriyaSubset = "latin" | "latin-ext" | "oriya";
export type NotoSansOriyaOptions = GoogleFontOptions<NotoSansOriyaWeight, NotoSansOriyaStyle, NotoSansOriyaSubset>;

/**
 * Noto Sans Oriya — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class NotoSansOriya extends GoogleFont<NotoSansOriyaWeight, NotoSansOriyaStyle, NotoSansOriyaSubset> {
  constructor(options?: NotoSansOriyaOptions) {
    super(FAMILY, FACES, options);
  }
}
