// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Noto Sans Vithkuqi";

const FACES = {
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/notosansvithkuqi/v3/jVyX7m77CXvQswd6WjYu9E1wN6cih2T4fj31.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/notosansvithkuqi/v3/jVyX7m77CXvQswd6WjYu9E1wN6cih2T4fj31.woff2",
    "600-normal":
      "https://fonts.gstatic.com/s/notosansvithkuqi/v3/jVyX7m77CXvQswd6WjYu9E1wN6cih2T4fj31.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/notosansvithkuqi/v3/jVyX7m77CXvQswd6WjYu9E1wN6cih2T4fj31.woff2",
  },
  "latin-ext": {
    "400-normal":
      "https://fonts.gstatic.com/s/notosansvithkuqi/v3/jVyX7m77CXvQswd6WjYu9E1wN6cih2T4cD31eZQ.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/notosansvithkuqi/v3/jVyX7m77CXvQswd6WjYu9E1wN6cih2T4cD31eZQ.woff2",
    "600-normal":
      "https://fonts.gstatic.com/s/notosansvithkuqi/v3/jVyX7m77CXvQswd6WjYu9E1wN6cih2T4cD31eZQ.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/notosansvithkuqi/v3/jVyX7m77CXvQswd6WjYu9E1wN6cih2T4cD31eZQ.woff2",
  },
  vithkuqi: {
    "400-normal":
      "https://fonts.gstatic.com/s/notosansvithkuqi/v3/jVyX7m77CXvQswd6WjYu9E1wN6cih2T4yxzQRK2K.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/notosansvithkuqi/v3/jVyX7m77CXvQswd6WjYu9E1wN6cih2T4yxzQRK2K.woff2",
    "600-normal":
      "https://fonts.gstatic.com/s/notosansvithkuqi/v3/jVyX7m77CXvQswd6WjYu9E1wN6cih2T4yxzQRK2K.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/notosansvithkuqi/v3/jVyX7m77CXvQswd6WjYu9E1wN6cih2T4yxzQRK2K.woff2",
  },
} as const;

export type NotoSansVithkuqiWeight = "400" | "500" | "600" | "700";
export type NotoSansVithkuqiStyle = "normal";
export type NotoSansVithkuqiSubset = "latin" | "latin-ext" | "vithkuqi";
export type NotoSansVithkuqiOptions = GoogleFontOptions<
  NotoSansVithkuqiWeight,
  NotoSansVithkuqiStyle,
  NotoSansVithkuqiSubset
>;

/**
 * Noto Sans Vithkuqi — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class NotoSansVithkuqi extends GoogleFont<
  NotoSansVithkuqiWeight,
  NotoSansVithkuqiStyle,
  NotoSansVithkuqiSubset
> {
  constructor(options?: NotoSansVithkuqiOptions) {
    super(FAMILY, FACES, options);
  }
}
