// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Noto Sans Caucasian Albanian";

const FACES = {
  "caucasian-albanian": {
    "400-normal":
      "https://fonts.gstatic.com/s/notosanscaucasianalbanian/v19/nKKA-HM_FYFRJvXzVXaANsU0VzsAc46QGOkWytlTs-TXnQPNhVSoUA.woff2",
  },
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/notosanscaucasianalbanian/v19/nKKA-HM_FYFRJvXzVXaANsU0VzsAc46QGOkWytlTs-TXnYfsoA.woff2",
  },
  "latin-ext": {
    "400-normal":
      "https://fonts.gstatic.com/s/notosanscaucasianalbanian/v19/nKKA-HM_FYFRJvXzVXaANsU0VzsAc46QGOkWytlTs-TXnYnsoGmR.woff2",
  },
} as const;

export type NotoSansCaucasianAlbanianWeight = "400";
export type NotoSansCaucasianAlbanianStyle = "normal";
export type NotoSansCaucasianAlbanianSubset = "caucasian-albanian" | "latin" | "latin-ext";
export type NotoSansCaucasianAlbanianOptions = GoogleFontOptions<
  NotoSansCaucasianAlbanianWeight,
  NotoSansCaucasianAlbanianStyle,
  NotoSansCaucasianAlbanianSubset
>;

/**
 * Noto Sans Caucasian Albanian — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class NotoSansCaucasianAlbanian extends GoogleFont<
  NotoSansCaucasianAlbanianWeight,
  NotoSansCaucasianAlbanianStyle,
  NotoSansCaucasianAlbanianSubset
> {
  constructor(options?: NotoSansCaucasianAlbanianOptions) {
    super(FAMILY, FACES, options);
  }
}
