// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Noto Sans Thaana";

const FACES = {
  "latin": {
    "100-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTu07rA.woff2",
    "200-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTu07rA.woff2",
    "300-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTu07rA.woff2",
    "400-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTu07rA.woff2",
    "500-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTu07rA.woff2",
    "600-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTu07rA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTu07rA.woff2",
    "800-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTu07rA.woff2",
    "900-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTu07rA.woff2",
  },
  "latin-ext": {
    "100-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTuM7rBKM.woff2",
    "200-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTuM7rBKM.woff2",
    "300-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTuM7rBKM.woff2",
    "400-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTuM7rBKM.woff2",
    "500-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTuM7rBKM.woff2",
    "600-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTuM7rBKM.woff2",
    "700-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTuM7rBKM.woff2",
    "800-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTuM7rBKM.woff2",
    "900-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTuM7rBKM.woff2",
  },
  "thaana": {
    "100-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTs87rBKM.woff2",
    "200-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTs87rBKM.woff2",
    "300-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTs87rBKM.woff2",
    "400-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTs87rBKM.woff2",
    "500-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTs87rBKM.woff2",
    "600-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTs87rBKM.woff2",
    "700-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTs87rBKM.woff2",
    "800-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTs87rBKM.woff2",
    "900-normal": "https://fonts.gstatic.com/s/notosansthaana/v26/C8c44dM-vnz-s-3jaEsxlxHkBH-WTs87rBKM.woff2",
  },
} as const;

export type NotoSansThaanaWeight = "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900";
export type NotoSansThaanaStyle = "normal";
export type NotoSansThaanaSubset = "latin" | "latin-ext" | "thaana";
export type NotoSansThaanaOptions = GoogleFontOptions<NotoSansThaanaWeight, NotoSansThaanaStyle, NotoSansThaanaSubset>;

/**
 * Noto Sans Thaana — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class NotoSansThaana extends GoogleFont<NotoSansThaanaWeight, NotoSansThaanaStyle, NotoSansThaanaSubset> {
  constructor(options?: NotoSansThaanaOptions) {
    super(FAMILY, FACES, options);
  }
}
