// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Noto Sans Hanifi Rohingya";

const FACES = {
  "hanifi-rohingya": {
    "400-normal": "https://fonts.gstatic.com/s/notosanshanifirohingya/v30/5h1IiYsoOmIC3Yu3MDXLDw3UZCgghyOEBBY7hhLN4OnFeEAy.woff2",
    "500-normal": "https://fonts.gstatic.com/s/notosanshanifirohingya/v30/5h1IiYsoOmIC3Yu3MDXLDw3UZCgghyOEBBY7hhLN4OnFeEAy.woff2",
    "600-normal": "https://fonts.gstatic.com/s/notosanshanifirohingya/v30/5h1IiYsoOmIC3Yu3MDXLDw3UZCgghyOEBBY7hhLN4OnFeEAy.woff2",
    "700-normal": "https://fonts.gstatic.com/s/notosanshanifirohingya/v30/5h1IiYsoOmIC3Yu3MDXLDw3UZCgghyOEBBY7hhLN4OnFeEAy.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/notosanshanifirohingya/v30/5h1IiYsoOmIC3Yu3MDXLDw3UZCgghyOEBBY7hhLN4IHFeA.woff2",
    "500-normal": "https://fonts.gstatic.com/s/notosanshanifirohingya/v30/5h1IiYsoOmIC3Yu3MDXLDw3UZCgghyOEBBY7hhLN4IHFeA.woff2",
    "600-normal": "https://fonts.gstatic.com/s/notosanshanifirohingya/v30/5h1IiYsoOmIC3Yu3MDXLDw3UZCgghyOEBBY7hhLN4IHFeA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/notosanshanifirohingya/v30/5h1IiYsoOmIC3Yu3MDXLDw3UZCgghyOEBBY7hhLN4IHFeA.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/notosanshanifirohingya/v30/5h1IiYsoOmIC3Yu3MDXLDw3UZCgghyOEBBY7hhLN4I_FeEAy.woff2",
    "500-normal": "https://fonts.gstatic.com/s/notosanshanifirohingya/v30/5h1IiYsoOmIC3Yu3MDXLDw3UZCgghyOEBBY7hhLN4I_FeEAy.woff2",
    "600-normal": "https://fonts.gstatic.com/s/notosanshanifirohingya/v30/5h1IiYsoOmIC3Yu3MDXLDw3UZCgghyOEBBY7hhLN4I_FeEAy.woff2",
    "700-normal": "https://fonts.gstatic.com/s/notosanshanifirohingya/v30/5h1IiYsoOmIC3Yu3MDXLDw3UZCgghyOEBBY7hhLN4I_FeEAy.woff2",
  },
} as const;

export type NotoSansHanifiRohingyaWeight = "400" | "500" | "600" | "700";
export type NotoSansHanifiRohingyaStyle = "normal";
export type NotoSansHanifiRohingyaSubset = "hanifi-rohingya" | "latin" | "latin-ext";
export type NotoSansHanifiRohingyaOptions = GoogleFontOptions<NotoSansHanifiRohingyaWeight, NotoSansHanifiRohingyaStyle, NotoSansHanifiRohingyaSubset>;

/**
 * Noto Sans Hanifi Rohingya — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class NotoSansHanifiRohingya extends GoogleFont<NotoSansHanifiRohingyaWeight, NotoSansHanifiRohingyaStyle, NotoSansHanifiRohingyaSubset> {
  constructor(options?: NotoSansHanifiRohingyaOptions) {
    super(FAMILY, FACES, options);
  }
}
