// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Paprika";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/paprika/v24/8QIJdijZitv49rDfiI8Eqg.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/paprika/v24/8QIJdijZitv49rDfiIEEqojk.woff2",
  },
} as const;

export type PaprikaWeight = "400";
export type PaprikaStyle = "normal";
export type PaprikaSubset = "latin" | "latin-ext";
export type PaprikaOptions = GoogleFontOptions<PaprikaWeight, PaprikaStyle, PaprikaSubset>;

/**
 * Paprika — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Paprika extends GoogleFont<PaprikaWeight, PaprikaStyle, PaprikaSubset> {
  constructor(options?: PaprikaOptions) {
    super(FAMILY, FACES, options);
  }
}
