// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Patrick Hand SC";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/patrickhandsc/v17/0nkwC9f7MfsBiWcLtY65AWDK873ljiK7.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/patrickhandsc/v17/0nkwC9f7MfsBiWcLtY65AWDK873lgCK7FQc.woff2",
  },
  "vietnamese": {
    "400-normal": "https://fonts.gstatic.com/s/patrickhandsc/v17/0nkwC9f7MfsBiWcLtY65AWDK873lgSK7FQc.woff2",
  },
} as const;

export type PatrickHandSCWeight = "400";
export type PatrickHandSCStyle = "normal";
export type PatrickHandSCSubset = "latin" | "latin-ext" | "vietnamese";
export type PatrickHandSCOptions = GoogleFontOptions<PatrickHandSCWeight, PatrickHandSCStyle, PatrickHandSCSubset>;

/**
 * Patrick Hand SC — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class PatrickHandSC extends GoogleFont<PatrickHandSCWeight, PatrickHandSCStyle, PatrickHandSCSubset> {
  constructor(options?: PatrickHandSCOptions) {
    super(FAMILY, FACES, options);
  }
}
