// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Playwrite NL Guides";

const FACES = {
  fallback: {
    "400-normal":
      "https://fonts.gstatic.com/s/playwritenlguides/v1/FwZH7_8mxlw-50y5PJughoCL4jbXkMqwsWc.woff2",
  },
} as const;

export type PlaywriteNLGuidesWeight = "400";
export type PlaywriteNLGuidesStyle = "normal";
export type PlaywriteNLGuidesSubset = "fallback";
export type PlaywriteNLGuidesOptions = GoogleFontOptions<
  PlaywriteNLGuidesWeight,
  PlaywriteNLGuidesStyle,
  PlaywriteNLGuidesSubset
>;

/**
 * Playwrite NL Guides — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class PlaywriteNLGuides extends GoogleFont<
  PlaywriteNLGuidesWeight,
  PlaywriteNLGuidesStyle,
  PlaywriteNLGuidesSubset
> {
  constructor(options?: PlaywriteNLGuidesOptions) {
    super(FAMILY, FACES, options);
  }
}
