// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Playwrite ZA";

const FACES = {
  "fallback": {
    "100-normal": "https://fonts.gstatic.com/s/playwriteza/v11/Noa16Uzhw5CTOhXKt5-vwvhxOQ.woff2",
    "200-normal": "https://fonts.gstatic.com/s/playwriteza/v11/Noa16Uzhw5CTOhXKt5-vwvhxOQ.woff2",
    "300-normal": "https://fonts.gstatic.com/s/playwriteza/v11/Noa16Uzhw5CTOhXKt5-vwvhxOQ.woff2",
    "400-normal": "https://fonts.gstatic.com/s/playwriteza/v11/Noa16Uzhw5CTOhXKt5-vwvhxOQ.woff2",
  },
} as const;

export type PlaywriteZAWeight = "100" | "200" | "300" | "400";
export type PlaywriteZAStyle = "normal";
export type PlaywriteZASubset = "fallback";
export type PlaywriteZAOptions = GoogleFontOptions<PlaywriteZAWeight, PlaywriteZAStyle, PlaywriteZASubset>;

/**
 * Playwrite ZA — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class PlaywriteZA extends GoogleFont<PlaywriteZAWeight, PlaywriteZAStyle, PlaywriteZASubset> {
  constructor(options?: PlaywriteZAOptions) {
    super(FAMILY, FACES, options);
  }
}
