// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Playwrite DE SAS";

const FACES = {
  "fallback": {
    "100-normal": "https://fonts.gstatic.com/s/playwritedesas/v11/1Pt1g9vaRvmWghDdrE8IDuRPVrHN5V4.woff2",
    "200-normal": "https://fonts.gstatic.com/s/playwritedesas/v11/1Pt1g9vaRvmWghDdrE8IDuRPVrHN5V4.woff2",
    "300-normal": "https://fonts.gstatic.com/s/playwritedesas/v11/1Pt1g9vaRvmWghDdrE8IDuRPVrHN5V4.woff2",
    "400-normal": "https://fonts.gstatic.com/s/playwritedesas/v11/1Pt1g9vaRvmWghDdrE8IDuRPVrHN5V4.woff2",
  },
} as const;

export type PlaywriteDESASWeight = "100" | "200" | "300" | "400";
export type PlaywriteDESASStyle = "normal";
export type PlaywriteDESASSubset = "fallback";
export type PlaywriteDESASOptions = GoogleFontOptions<PlaywriteDESASWeight, PlaywriteDESASStyle, PlaywriteDESASSubset>;

/**
 * Playwrite DE SAS — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class PlaywriteDESAS extends GoogleFont<PlaywriteDESASWeight, PlaywriteDESASStyle, PlaywriteDESASSubset> {
  constructor(options?: PlaywriteDESASOptions) {
    super(FAMILY, FACES, options);
  }
}
