// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Playwrite AU VIC";

const FACES = {
  fallback: {
    "100-normal":
      "https://fonts.gstatic.com/s/playwriteauvic/v11/bWtj7enUfwn0Hf1zjprKOJdcDy8r3Q4.woff2",
    "200-normal":
      "https://fonts.gstatic.com/s/playwriteauvic/v11/bWtj7enUfwn0Hf1zjprKOJdcDy8r3Q4.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/playwriteauvic/v11/bWtj7enUfwn0Hf1zjprKOJdcDy8r3Q4.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/playwriteauvic/v11/bWtj7enUfwn0Hf1zjprKOJdcDy8r3Q4.woff2",
  },
} as const;

export type PlaywriteAUVICWeight = "100" | "200" | "300" | "400";
export type PlaywriteAUVICStyle = "normal";
export type PlaywriteAUVICSubset = "fallback";
export type PlaywriteAUVICOptions = GoogleFontOptions<
  PlaywriteAUVICWeight,
  PlaywriteAUVICStyle,
  PlaywriteAUVICSubset
>;

/**
 * Playwrite AU VIC — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class PlaywriteAUVIC extends GoogleFont<
  PlaywriteAUVICWeight,
  PlaywriteAUVICStyle,
  PlaywriteAUVICSubset
> {
  constructor(options?: PlaywriteAUVICOptions) {
    super(FAMILY, FACES, options);
  }
}
