// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Pragati Narrow";

const FACES = {
  "devanagari": {
    "400-normal": "https://fonts.gstatic.com/s/pragatinarrow/v15/vm8vdRf0T0bS1ffgsPB7WZ-mD275wNJHMw.woff2",
    "700-normal": "https://fonts.gstatic.com/s/pragatinarrow/v15/vm8sdRf0T0bS1ffgsPB7WZ-mD2ZD5cd5EpIjlg.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/pragatinarrow/v15/vm8vdRf0T0bS1ffgsPB7WZ-mD274wNI.woff2",
    "700-normal": "https://fonts.gstatic.com/s/pragatinarrow/v15/vm8sdRf0T0bS1ffgsPB7WZ-mD2ZD5cd4EpI.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/pragatinarrow/v15/vm8vdRf0T0bS1ffgsPB7WZ-mD272wNJHMw.woff2",
    "700-normal": "https://fonts.gstatic.com/s/pragatinarrow/v15/vm8sdRf0T0bS1ffgsPB7WZ-mD2ZD5cd2EpIjlg.woff2",
  },
} as const;

export type PragatiNarrowWeight = "400" | "700";
export type PragatiNarrowStyle = "normal";
export type PragatiNarrowSubset = "devanagari" | "latin" | "latin-ext";
export type PragatiNarrowOptions = GoogleFontOptions<PragatiNarrowWeight, PragatiNarrowStyle, PragatiNarrowSubset>;

/**
 * Pragati Narrow — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class PragatiNarrow extends GoogleFont<PragatiNarrowWeight, PragatiNarrowStyle, PragatiNarrowSubset> {
  constructor(options?: PragatiNarrowOptions) {
    super(FAMILY, FACES, options);
  }
}
