// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Prompt";

const FACES = {
  latin: {
    "100-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_7XJnvUD7dzB2KZeJ8fkQLfg.woff2",
    "100-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_9XJnvUD7dzB2CA-ofTkY.woff2",
    "200-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeLQb1MsW5A.woff2",
    "200-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cr_sIaWMu.woff2",
    "300-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeK0bFMsW5A.woff2",
    "300-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cy_gIaWMu.woff2",
    "400-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_9XJnvUD7dzB2KZeofTkY.woff2",
    "400-normal": "https://fonts.gstatic.com/s/prompt/v12/-W__XJnvUD7dzB2KYNod.woff2",
    "500-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeLsbVMsW5A.woff2",
    "500-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Ck_kIaWMu.woff2",
    "600-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeLAalMsW5A.woff2",
    "600-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cv_4IaWMu.woff2",
    "700-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeKka1MsW5A.woff2",
    "700-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2C2_8IaWMu.woff2",
    "800-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeK4aFMsW5A.woff2",
    "800-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cx_wIaWMu.woff2",
    "900-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeKcaVMsW5A.woff2",
    "900-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2C4_0IaWMu.woff2",
  },
  "latin-ext": {
    "100-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_7XJnvUD7dzB2KZeJ8fkoLfq0k.woff2",
    "100-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_9XJnvUD7dzB2CA-oRTkYTeg.woff2",
    "200-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeLQb1MiW5Addw.woff2",
    "200-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cr_sIZ2MuQ5Q.woff2",
    "300-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeK0bFMiW5Addw.woff2",
    "300-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cy_gIZ2MuQ5Q.woff2",
    "400-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_9XJnvUD7dzB2KZeoRTkYTeg.woff2",
    "400-normal": "https://fonts.gstatic.com/s/prompt/v12/-W__XJnvUD7dzB2KbtodVkI.woff2",
    "500-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeLsbVMiW5Addw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Ck_kIZ2MuQ5Q.woff2",
    "600-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeLAalMiW5Addw.woff2",
    "600-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cv_4IZ2MuQ5Q.woff2",
    "700-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeKka1MiW5Addw.woff2",
    "700-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2C2_8IZ2MuQ5Q.woff2",
    "800-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeK4aFMiW5Addw.woff2",
    "800-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cx_wIZ2MuQ5Q.woff2",
    "900-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeKcaVMiW5Addw.woff2",
    "900-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2C4_0IZ2MuQ5Q.woff2",
  },
  thai: {
    "100-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_7XJnvUD7dzB2KZeJ8flALfq0k.woff2",
    "100-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_9XJnvUD7dzB2CA-oLTkYTeg.woff2",
    "200-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeLQb1M4W5Addw.woff2",
    "200-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cr_sIfWMuQ5Q.woff2",
    "300-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeK0bFM4W5Addw.woff2",
    "300-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cy_gIfWMuQ5Q.woff2",
    "400-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_9XJnvUD7dzB2KZeoLTkYTeg.woff2",
    "400-normal": "https://fonts.gstatic.com/s/prompt/v12/-W__XJnvUD7dzB2KdNodVkI.woff2",
    "500-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeLsbVM4W5Addw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Ck_kIfWMuQ5Q.woff2",
    "600-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeLAalM4W5Addw.woff2",
    "600-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cv_4IfWMuQ5Q.woff2",
    "700-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeKka1M4W5Addw.woff2",
    "700-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2C2_8IfWMuQ5Q.woff2",
    "800-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeK4aFM4W5Addw.woff2",
    "800-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cx_wIfWMuQ5Q.woff2",
    "900-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeKcaVM4W5Addw.woff2",
    "900-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2C4_0IfWMuQ5Q.woff2",
  },
  vietnamese: {
    "100-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_7XJnvUD7dzB2KZeJ8fksLfq0k.woff2",
    "100-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_9XJnvUD7dzB2CA-oQTkYTeg.woff2",
    "200-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeLQb1MjW5Addw.woff2",
    "200-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cr_sIZmMuQ5Q.woff2",
    "300-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeK0bFMjW5Addw.woff2",
    "300-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cy_gIZmMuQ5Q.woff2",
    "400-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_9XJnvUD7dzB2KZeoQTkYTeg.woff2",
    "400-normal": "https://fonts.gstatic.com/s/prompt/v12/-W__XJnvUD7dzB2Kb9odVkI.woff2",
    "500-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeLsbVMjW5Addw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Ck_kIZmMuQ5Q.woff2",
    "600-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeLAalMjW5Addw.woff2",
    "600-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cv_4IZmMuQ5Q.woff2",
    "700-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeKka1MjW5Addw.woff2",
    "700-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2C2_8IZmMuQ5Q.woff2",
    "800-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeK4aFMjW5Addw.woff2",
    "800-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2Cx_wIZmMuQ5Q.woff2",
    "900-italic": "https://fonts.gstatic.com/s/prompt/v12/-W_6XJnvUD7dzB2KZeKcaVMjW5Addw.woff2",
    "900-normal": "https://fonts.gstatic.com/s/prompt/v12/-W_8XJnvUD7dzB2C4_0IZmMuQ5Q.woff2",
  },
} as const;

export type PromptWeight = "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900";
export type PromptStyle = "italic" | "normal";
export type PromptSubset = "latin" | "latin-ext" | "thai" | "vietnamese";
export type PromptOptions = GoogleFontOptions<PromptWeight, PromptStyle, PromptSubset>;

/**
 * Prompt — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Prompt extends GoogleFont<PromptWeight, PromptStyle, PromptSubset> {
  constructor(options?: PromptOptions) {
    super(FAMILY, FACES, options);
  }
}
