// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Prosto One";

const FACES = {
  "cyrillic": {
    "400-normal": "https://fonts.gstatic.com/s/prostoone/v21/OpNJno4VhNfK-RgpwWWxlilVWyXD.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/prostoone/v21/OpNJno4VhNfK-RgpwWWxli1VWw.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/prostoone/v21/OpNJno4VhNfK-RgpwWWxliNVWyXD.woff2",
  },
} as const;

export type ProstoOneWeight = "400";
export type ProstoOneStyle = "normal";
export type ProstoOneSubset = "cyrillic" | "latin" | "latin-ext";
export type ProstoOneOptions = GoogleFontOptions<ProstoOneWeight, ProstoOneStyle, ProstoOneSubset>;

/**
 * Prosto One — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class ProstoOne extends GoogleFont<ProstoOneWeight, ProstoOneStyle, ProstoOneSubset> {
  constructor(options?: ProstoOneOptions) {
    super(FAMILY, FACES, options);
  }
}
