// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Protest Revolution";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/protestrevolution/v2/11hcGofZ0kXBbxQXFB7MJsjtqnVw6Z2c9_gy.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/protestrevolution/v2/11hcGofZ0kXBbxQXFB7MJsjtqnVw6Z2c-fgyfG0.woff2",
  },
  "math": {
    "400-normal": "https://fonts.gstatic.com/s/protestrevolution/v2/11hcGofZ0kXBbxQXFB7MJsjtqnVw6Z2ci_gyfG0.woff2",
  },
  "symbols": {
    "400-normal": "https://fonts.gstatic.com/s/protestrevolution/v2/11hcGofZ0kXBbxQXFB7MJsjtqnVw6Z2cmfgyfG0.woff2",
  },
  "vietnamese": {
    "400-normal": "https://fonts.gstatic.com/s/protestrevolution/v2/11hcGofZ0kXBbxQXFB7MJsjtqnVw6Z2c-PgyfG0.woff2",
  },
} as const;

export type ProtestRevolutionWeight = "400";
export type ProtestRevolutionStyle = "normal";
export type ProtestRevolutionSubset = "latin" | "latin-ext" | "math" | "symbols" | "vietnamese";
export type ProtestRevolutionOptions = GoogleFontOptions<ProtestRevolutionWeight, ProtestRevolutionStyle, ProtestRevolutionSubset>;

/**
 * Protest Revolution — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class ProtestRevolution extends GoogleFont<ProtestRevolutionWeight, ProtestRevolutionStyle, ProtestRevolutionSubset> {
  constructor(options?: ProtestRevolutionOptions) {
    super(FAMILY, FACES, options);
  }
}
