// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Questrial";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/questrial/v19/QdVUSTchPBm7nuUeVf70viFl.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/questrial/v19/QdVUSTchPBm7nuUeVf70sCFlq20.woff2",
  },
  vietnamese: {
    "400-normal": "https://fonts.gstatic.com/s/questrial/v19/QdVUSTchPBm7nuUeVf70sSFlq20.woff2",
  },
} as const;

export type QuestrialWeight = "400";
export type QuestrialStyle = "normal";
export type QuestrialSubset = "latin" | "latin-ext" | "vietnamese";
export type QuestrialOptions = GoogleFontOptions<QuestrialWeight, QuestrialStyle, QuestrialSubset>;

/**
 * Questrial — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Questrial extends GoogleFont<
  QuestrialWeight,
  QuestrialStyle,
  QuestrialSubset
> {
  constructor(options?: QuestrialOptions) {
    super(FAMILY, FACES, options);
  }
}
