// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Radley";

const FACES = {
  "latin": {
    "400-italic": "https://fonts.gstatic.com/s/radley/v24/LYjBdGzinEIjCN1NojNHjV8.woff2",
    "400-normal": "https://fonts.gstatic.com/s/radley/v24/LYjDdGzinEIjCN1NpwNF.woff2",
  },
  "latin-ext": {
    "400-italic": "https://fonts.gstatic.com/s/radley/v24/LYjBdGzinEIjCN1NojNJjV8XVQ.woff2",
    "400-normal": "https://fonts.gstatic.com/s/radley/v24/LYjDdGzinEIjCN1NqQNFlVs.woff2",
  },
} as const;

export type RadleyWeight = "400";
export type RadleyStyle = "italic" | "normal";
export type RadleySubset = "latin" | "latin-ext";
export type RadleyOptions = GoogleFontOptions<RadleyWeight, RadleyStyle, RadleySubset>;

/**
 * Radley — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Radley extends GoogleFont<RadleyWeight, RadleyStyle, RadleySubset> {
  constructor(options?: RadleyOptions) {
    super(FAMILY, FACES, options);
  }
}
