// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Ramsina";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/ramsina/v3/daaYSTE-LGmCbhP9yLk_Qg.woff2",
  },
  "syriac": {
    "400-normal": "https://fonts.gstatic.com/s/ramsina/v3/daaYSTE-LGmCbhP9yMo_QrmM.woff2",
  },
} as const;

export type RamsinaWeight = "400";
export type RamsinaStyle = "normal";
export type RamsinaSubset = "latin" | "syriac";
export type RamsinaOptions = GoogleFontOptions<RamsinaWeight, RamsinaStyle, RamsinaSubset>;

/**
 * Ramsina — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Ramsina extends GoogleFont<RamsinaWeight, RamsinaStyle, RamsinaSubset> {
  constructor(options?: RamsinaOptions) {
    super(FAMILY, FACES, options);
  }
}
