// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Red Hat Mono";

const FACES = {
  latin: {
    "300-italic":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyT7nDnA2uf2zVvFAhhzEsUXdxQ1gg.woff2",
    "300-normal": "https://fonts.gstatic.com/s/redhatmono/v16/jVyN7nDnA2uf2zVvFAhhzEsUWOxS.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyT7nDnA2uf2zVvFAhhzEsUXdxQ1gg.woff2",
    "400-normal": "https://fonts.gstatic.com/s/redhatmono/v16/jVyN7nDnA2uf2zVvFAhhzEsUWOxS.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyT7nDnA2uf2zVvFAhhzEsUXdxQ1gg.woff2",
    "500-normal": "https://fonts.gstatic.com/s/redhatmono/v16/jVyN7nDnA2uf2zVvFAhhzEsUWOxS.woff2",
    "600-italic":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyT7nDnA2uf2zVvFAhhzEsUXdxQ1gg.woff2",
    "600-normal": "https://fonts.gstatic.com/s/redhatmono/v16/jVyN7nDnA2uf2zVvFAhhzEsUWOxS.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyT7nDnA2uf2zVvFAhhzEsUXdxQ1gg.woff2",
    "700-normal": "https://fonts.gstatic.com/s/redhatmono/v16/jVyN7nDnA2uf2zVvFAhhzEsUWOxS.woff2",
  },
  "latin-ext": {
    "300-italic":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyT7nDnA2uf2zVvFAhhzEsUXdxe1gjQeA.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyN7nDnA2uf2zVvFAhhzEsUVuxSzgw.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyT7nDnA2uf2zVvFAhhzEsUXdxe1gjQeA.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyN7nDnA2uf2zVvFAhhzEsUVuxSzgw.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyT7nDnA2uf2zVvFAhhzEsUXdxe1gjQeA.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyN7nDnA2uf2zVvFAhhzEsUVuxSzgw.woff2",
    "600-italic":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyT7nDnA2uf2zVvFAhhzEsUXdxe1gjQeA.woff2",
    "600-normal":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyN7nDnA2uf2zVvFAhhzEsUVuxSzgw.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyT7nDnA2uf2zVvFAhhzEsUXdxe1gjQeA.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/redhatmono/v16/jVyN7nDnA2uf2zVvFAhhzEsUVuxSzgw.woff2",
  },
} as const;

export type RedHatMonoWeight = "300" | "400" | "500" | "600" | "700";
export type RedHatMonoStyle = "italic" | "normal";
export type RedHatMonoSubset = "latin" | "latin-ext";
export type RedHatMonoOptions = GoogleFontOptions<
  RedHatMonoWeight,
  RedHatMonoStyle,
  RedHatMonoSubset
>;

/**
 * Red Hat Mono — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class RedHatMono extends GoogleFont<
  RedHatMonoWeight,
  RedHatMonoStyle,
  RedHatMonoSubset
> {
  constructor(options?: RedHatMonoOptions) {
    super(FAMILY, FACES, options);
  }
}
