// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "REM";

const FACES = {
  latin: {
    "100-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAsQRM.woff2",
    "100-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytYTAu.woff2",
    "200-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAsQRM.woff2",
    "200-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytYTAu.woff2",
    "300-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAsQRM.woff2",
    "300-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytYTAu.woff2",
    "400-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAsQRM.woff2",
    "400-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytYTAu.woff2",
    "500-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAsQRM.woff2",
    "500-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytYTAu.woff2",
    "600-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAsQRM.woff2",
    "600-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytYTAu.woff2",
    "700-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAsQRM.woff2",
    "700-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytYTAu.woff2",
    "800-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAsQRM.woff2",
    "800-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytYTAu.woff2",
    "900-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAsQRM.woff2",
    "900-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytYTAu.woff2",
  },
  "latin-ext": {
    "100-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAiQRMlow.woff2",
    "100-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbzAuWRc.woff2",
    "200-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAiQRMlow.woff2",
    "200-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbzAuWRc.woff2",
    "300-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAiQRMlow.woff2",
    "300-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbzAuWRc.woff2",
    "400-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAiQRMlow.woff2",
    "400-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbzAuWRc.woff2",
    "500-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAiQRMlow.woff2",
    "500-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbzAuWRc.woff2",
    "600-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAiQRMlow.woff2",
    "600-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbzAuWRc.woff2",
    "700-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAiQRMlow.woff2",
    "700-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbzAuWRc.woff2",
    "800-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAiQRMlow.woff2",
    "800-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbzAuWRc.woff2",
    "900-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAiQRMlow.woff2",
    "900-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbzAuWRc.woff2",
  },
  vietnamese: {
    "100-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAjQRMlow.woff2",
    "100-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbjAuWRc.woff2",
    "200-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAjQRMlow.woff2",
    "200-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbjAuWRc.woff2",
    "300-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAjQRMlow.woff2",
    "300-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbjAuWRc.woff2",
    "400-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAjQRMlow.woff2",
    "400-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbjAuWRc.woff2",
    "500-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAjQRMlow.woff2",
    "500-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbjAuWRc.woff2",
    "600-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAjQRMlow.woff2",
    "600-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbjAuWRc.woff2",
    "700-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAjQRMlow.woff2",
    "700-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbjAuWRc.woff2",
    "800-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAjQRMlow.woff2",
    "800-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbjAuWRc.woff2",
    "900-italic": "https://fonts.gstatic.com/s/rem/v4/Wnz1HAIoSDytZAAjQRMlow.woff2",
    "900-normal": "https://fonts.gstatic.com/s/rem/v4/Wnz3HAIoSDytbjAuWRc.woff2",
  },
} as const;

export type REMWeight = "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900";
export type REMStyle = "italic" | "normal";
export type REMSubset = "latin" | "latin-ext" | "vietnamese";
export type REMOptions = GoogleFontOptions<REMWeight, REMStyle, REMSubset>;

/**
 * REM — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class REM extends GoogleFont<REMWeight, REMStyle, REMSubset> {
  constructor(options?: REMOptions) {
    super(FAMILY, FACES, options);
  }
}
