// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Risque";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/risque/v24/VdGfAZUfHosahXxYDkwU.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/risque/v24/VdGfAZUfHosahXxYAEwUNJ8.woff2",
  },
} as const;

export type RisqueWeight = "400";
export type RisqueStyle = "normal";
export type RisqueSubset = "latin" | "latin-ext";
export type RisqueOptions = GoogleFontOptions<RisqueWeight, RisqueStyle, RisqueSubset>;

/**
 * Risque — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Risque extends GoogleFont<RisqueWeight, RisqueStyle, RisqueSubset> {
  constructor(options?: RisqueOptions) {
    super(FAMILY, FACES, options);
  }
}
