// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Rozha One";

const FACES = {
  "devanagari": {
    "400-normal": "https://fonts.gstatic.com/s/rozhaone/v17/AlZy_zVFtYP12Zncg2kRc335bB0.woff2",
  },
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/rozhaone/v17/AlZy_zVFtYP12Zncg2kRcn35.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/rozhaone/v17/AlZy_zVFtYP12Zncg2kRfH35bB0.woff2",
  },
} as const;

export type RozhaOneWeight = "400";
export type RozhaOneStyle = "normal";
export type RozhaOneSubset = "devanagari" | "latin" | "latin-ext";
export type RozhaOneOptions = GoogleFontOptions<RozhaOneWeight, RozhaOneStyle, RozhaOneSubset>;

/**
 * Rozha One — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class RozhaOne extends GoogleFont<RozhaOneWeight, RozhaOneStyle, RozhaOneSubset> {
  constructor(options?: RozhaOneOptions) {
    super(FAMILY, FACES, options);
  }
}
