// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Ruthie";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/ruthie/v28/gokvH63sGkdqXuUNkzR2.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/ruthie/v28/gokvH63sGkdqXuUNnTR2c2s.woff2",
  },
  "vietnamese": {
    "400-normal": "https://fonts.gstatic.com/s/ruthie/v28/gokvH63sGkdqXuUNnDR2c2s.woff2",
  },
} as const;

export type RuthieWeight = "400";
export type RuthieStyle = "normal";
export type RuthieSubset = "latin" | "latin-ext" | "vietnamese";
export type RuthieOptions = GoogleFontOptions<RuthieWeight, RuthieStyle, RuthieSubset>;

/**
 * Ruthie — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Ruthie extends GoogleFont<RuthieWeight, RuthieStyle, RuthieSubset> {
  constructor(options?: RuthieOptions) {
    super(FAMILY, FACES, options);
  }
}
