// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Ruwudu";

const FACES = {
  arabic: {
    "400-normal": "https://fonts.gstatic.com/s/ruwudu/v4/syky-y1tj6UzRKf9lwqSxtM.woff2",
    "500-normal": "https://fonts.gstatic.com/s/ruwudu/v4/sykx-y1tj6UzRKf1YSmH_PLAnlQ.woff2",
    "600-normal": "https://fonts.gstatic.com/s/ruwudu/v4/sykx-y1tj6UzRKf1TS6H_PLAnlQ.woff2",
    "700-normal": "https://fonts.gstatic.com/s/ruwudu/v4/sykx-y1tj6UzRKf1KS-H_PLAnlQ.woff2",
  },
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/ruwudu/v4/syky-y1tj6UzRKf9kgqS.woff2",
    "500-normal": "https://fonts.gstatic.com/s/ruwudu/v4/sykx-y1tj6UzRKf1YSmH-fLA.woff2",
    "600-normal": "https://fonts.gstatic.com/s/ruwudu/v4/sykx-y1tj6UzRKf1TS6H-fLA.woff2",
    "700-normal": "https://fonts.gstatic.com/s/ruwudu/v4/sykx-y1tj6UzRKf1KS-H-fLA.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/ruwudu/v4/syky-y1tj6UzRKf9nAqSxtM.woff2",
    "500-normal": "https://fonts.gstatic.com/s/ruwudu/v4/sykx-y1tj6UzRKf1YSmH9_LAnlQ.woff2",
    "600-normal": "https://fonts.gstatic.com/s/ruwudu/v4/sykx-y1tj6UzRKf1TS6H9_LAnlQ.woff2",
    "700-normal": "https://fonts.gstatic.com/s/ruwudu/v4/sykx-y1tj6UzRKf1KS-H9_LAnlQ.woff2",
  },
} as const;

export type RuwuduWeight = "400" | "500" | "600" | "700";
export type RuwuduStyle = "normal";
export type RuwuduSubset = "arabic" | "latin" | "latin-ext";
export type RuwuduOptions = GoogleFontOptions<RuwuduWeight, RuwuduStyle, RuwuduSubset>;

/**
 * Ruwudu — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Ruwudu extends GoogleFont<RuwuduWeight, RuwuduStyle, RuwuduSubset> {
  constructor(options?: RuwuduOptions) {
    super(FAMILY, FACES, options);
  }
}
