// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Sail";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/sail/v17/DPEjYwiBxwYJJBPJAQ.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/sail/v17/DPEjYwiBxwYJJB3JAQYA.woff2",
  },
} as const;

export type SailWeight = "400";
export type SailStyle = "normal";
export type SailSubset = "latin" | "latin-ext";
export type SailOptions = GoogleFontOptions<SailWeight, SailStyle, SailSubset>;

/**
 * Sail — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Sail extends GoogleFont<SailWeight, SailStyle, SailSubset> {
  constructor(options?: SailOptions) {
    super(FAMILY, FACES, options);
  }
}
