// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Sankofa Display";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/sankofadisplay/v2/Ktk1ALSRd4LucUDghJ2rTqXOoh3HEKOY.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/sankofadisplay/v2/Ktk1ALSRd4LucUDghJ2rTqXOoh3HHqOYZY8.woff2",
  },
  "vietnamese": {
    "400-normal": "https://fonts.gstatic.com/s/sankofadisplay/v2/Ktk1ALSRd4LucUDghJ2rTqXOoh3HH6OYZY8.woff2",
  },
} as const;

export type SankofaDisplayWeight = "400";
export type SankofaDisplayStyle = "normal";
export type SankofaDisplaySubset = "latin" | "latin-ext" | "vietnamese";
export type SankofaDisplayOptions = GoogleFontOptions<SankofaDisplayWeight, SankofaDisplayStyle, SankofaDisplaySubset>;

/**
 * Sankofa Display — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class SankofaDisplay extends GoogleFont<SankofaDisplayWeight, SankofaDisplayStyle, SankofaDisplaySubset> {
  constructor(options?: SankofaDisplayOptions) {
    super(FAMILY, FACES, options);
  }
}
