// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Sarabun";

const FACES = {
  latin: {
    "100-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVnJx26TKEr37c9aBBx_kwLzg0.woff2",
    "100-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVhJx26TKEr37c9YHZ5nXwJ.woff2",
    "200-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxUl0c6SjT.woff2",
    "200-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YNpoilss6w.woff2",
    "300-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxNl4c6SjT.woff2",
    "300-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YL5rilss6w.woff2",
    "400-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVhJx26TKEr37c9aBB5nXwJ.woff2",
    "400-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVjJx26TKEr37c9aBVJnw.woff2",
    "500-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxbl8c6SjT.woff2",
    "500-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YOZqilss6w.woff2",
    "600-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxQlgc6SjT.woff2",
    "600-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YMptilss6w.woff2",
    "700-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxJlkc6SjT.woff2",
    "700-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YK5silss6w.woff2",
    "800-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxOloc6SjT.woff2",
    "800-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YLJvilss6w.woff2",
  },
  "latin-ext": {
    "100-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVnJx26TKEr37c9aBBx_kwFzg3upg.woff2",
    "100-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVhJx26TKEr37c9YHZ5k3wJ1gk.woff2",
    "200-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxUl0c5yjTnwE.woff2",
    "200-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YNpoilUs6zDX.woff2",
    "300-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxNl4c5yjTnwE.woff2",
    "300-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YL5rilUs6zDX.woff2",
    "400-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVhJx26TKEr37c9aBB5k3wJ1gk.woff2",
    "400-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVjJx26TKEr37c9aBtJn2QN.woff2",
    "500-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxbl8c5yjTnwE.woff2",
    "500-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YOZqilUs6zDX.woff2",
    "600-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxQlgc5yjTnwE.woff2",
    "600-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YMptilUs6zDX.woff2",
    "700-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxJlkc5yjTnwE.woff2",
    "700-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YK5silUs6zDX.woff2",
    "800-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxOloc5yjTnwE.woff2",
    "800-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YLJvilUs6zDX.woff2",
  },
  thai: {
    "100-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVnJx26TKEr37c9aBBx_kwfzg3upg.woff2",
    "100-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVhJx26TKEr37c9YHZ5iXwJ1gk.woff2",
    "200-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxUl0c_SjTnwE.woff2",
    "200-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YNpoik8s6zDX.woff2",
    "300-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxNl4c_SjTnwE.woff2",
    "300-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YL5rik8s6zDX.woff2",
    "400-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVhJx26TKEr37c9aBB5iXwJ1gk.woff2",
    "400-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVjJx26TKEr37c9aAFJn2QN.woff2",
    "500-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxbl8c_SjTnwE.woff2",
    "500-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YOZqik8s6zDX.woff2",
    "600-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxQlgc_SjTnwE.woff2",
    "600-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YMptik8s6zDX.woff2",
    "700-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxJlkc_SjTnwE.woff2",
    "700-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YK5sik8s6zDX.woff2",
    "800-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxOloc_SjTnwE.woff2",
    "800-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YLJvik8s6zDX.woff2",
  },
  vietnamese: {
    "100-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVnJx26TKEr37c9aBBx_kwEzg3upg.woff2",
    "100-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVhJx26TKEr37c9YHZ5knwJ1gk.woff2",
    "200-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxUl0c5ijTnwE.woff2",
    "200-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YNpoilQs6zDX.woff2",
    "300-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxNl4c5ijTnwE.woff2",
    "300-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YL5rilQs6zDX.woff2",
    "400-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVhJx26TKEr37c9aBB5knwJ1gk.woff2",
    "400-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVjJx26TKEr37c9aBpJn2QN.woff2",
    "500-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxbl8c5ijTnwE.woff2",
    "500-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YOZqilQs6zDX.woff2",
    "600-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxQlgc5ijTnwE.woff2",
    "600-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YMptilQs6zDX.woff2",
    "700-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxJlkc5ijTnwE.woff2",
    "700-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YK5silQs6zDX.woff2",
    "800-italic": "https://fonts.gstatic.com/s/sarabun/v17/DtVkJx26TKEr37c9aBBxOloc5ijTnwE.woff2",
    "800-normal": "https://fonts.gstatic.com/s/sarabun/v17/DtVmJx26TKEr37c9YLJvilQs6zDX.woff2",
  },
} as const;

export type SarabunWeight = "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800";
export type SarabunStyle = "italic" | "normal";
export type SarabunSubset = "latin" | "latin-ext" | "thai" | "vietnamese";
export type SarabunOptions = GoogleFontOptions<SarabunWeight, SarabunStyle, SarabunSubset>;

/**
 * Sarabun — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Sarabun extends GoogleFont<SarabunWeight, SarabunStyle, SarabunSubset> {
  constructor(options?: SarabunOptions) {
    super(FAMILY, FACES, options);
  }
}
