// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Share Tech Mono";

const FACES = {
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/sharetechmono/v16/J7aHnp1uDWRBEqV98dVQztYldFcLowEF.woff2",
  },
} as const;

export type ShareTechMonoWeight = "400";
export type ShareTechMonoStyle = "normal";
export type ShareTechMonoSubset = "latin";
export type ShareTechMonoOptions = GoogleFontOptions<
  ShareTechMonoWeight,
  ShareTechMonoStyle,
  ShareTechMonoSubset
>;

/**
 * Share Tech Mono — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class ShareTechMono extends GoogleFont<
  ShareTechMonoWeight,
  ShareTechMonoStyle,
  ShareTechMonoSubset
> {
  constructor(options?: ShareTechMonoOptions) {
    super(FAMILY, FACES, options);
  }
}
