// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Share";

const FACES = {
  "latin": {
    "400-italic": "https://fonts.gstatic.com/s/share/v20/i7dKIFliZjKNF6VPJrmedQ.woff2",
    "400-normal": "https://fonts.gstatic.com/s/share/v20/i7dEIFliZjKNF6VKFrs.woff2",
    "700-italic": "https://fonts.gstatic.com/s/share/v20/i7dPIFliZjKNF6VPLgK7YEF8RQ.woff2",
    "700-normal": "https://fonts.gstatic.com/s/share/v20/i7dJIFliZjKNF63xM665UEM.woff2",
  },
  "latin-ext": {
    "400-italic": "https://fonts.gstatic.com/s/share/v20/i7dKIFliZjKNF6VPJreedX5d.woff2",
    "400-normal": "https://fonts.gstatic.com/s/share/v20/i7dEIFliZjKNF6VEFruGcQ.woff2",
    "700-italic": "https://fonts.gstatic.com/s/share/v20/i7dPIFliZjKNF6VPLgK7YE98RWq7.woff2",
    "700-normal": "https://fonts.gstatic.com/s/share/v20/i7dJIFliZjKNF63xM663UENkQQ.woff2",
  },
} as const;

export type ShareWeight = "400" | "700";
export type ShareStyle = "italic" | "normal";
export type ShareSubset = "latin" | "latin-ext";
export type ShareOptions = GoogleFontOptions<ShareWeight, ShareStyle, ShareSubset>;

/**
 * Share — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Share extends GoogleFont<ShareWeight, ShareStyle, ShareSubset> {
  constructor(options?: ShareOptions) {
    super(FAMILY, FACES, options);
  }
}
