// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Sigmar";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/sigmar/v9/hv-XlzJgIE8a85pkamw2.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/sigmar/v9/hv-XlzJgIE8a85pkZGw2ATE.woff2",
  },
  "vietnamese": {
    "400-normal": "https://fonts.gstatic.com/s/sigmar/v9/hv-XlzJgIE8a85pkZWw2ATE.woff2",
  },
} as const;

export type SigmarWeight = "400";
export type SigmarStyle = "normal";
export type SigmarSubset = "latin" | "latin-ext" | "vietnamese";
export type SigmarOptions = GoogleFontOptions<SigmarWeight, SigmarStyle, SigmarSubset>;

/**
 * Sigmar — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Sigmar extends GoogleFont<SigmarWeight, SigmarStyle, SigmarSubset> {
  constructor(options?: SigmarOptions) {
    super(FAMILY, FACES, options);
  }
}
