// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Sintony";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/sintony/v17/XoHm2YDqR7-98cVUETMtug.woff2",
    "700-normal": "https://fonts.gstatic.com/s/sintony/v17/XoHj2YDqR7-98cVUGYgIr9AJkw.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/sintony/v17/XoHm2YDqR7-98cVUET0tuu8o.woff2",
    "700-normal": "https://fonts.gstatic.com/s/sintony/v17/XoHj2YDqR7-98cVUGYgIr94JkwLp.woff2",
  },
} as const;

export type SintonyWeight = "400" | "700";
export type SintonyStyle = "normal";
export type SintonySubset = "latin" | "latin-ext";
export type SintonyOptions = GoogleFontOptions<SintonyWeight, SintonyStyle, SintonySubset>;

/**
 * Sintony — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Sintony extends GoogleFont<SintonyWeight, SintonyStyle, SintonySubset> {
  constructor(options?: SintonyOptions) {
    super(FAMILY, FACES, options);
  }
}
