// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Slabo 27px";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/slabo27px/v16/mFT0WbgBwKPR_Z4hGN2qgx8D1Q.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/slabo27px/v16/mFT0WbgBwKPR_Z4hGN2qgxED1XJ7.woff2",
  },
} as const;

export type Slabo27pxWeight = "400";
export type Slabo27pxStyle = "normal";
export type Slabo27pxSubset = "latin" | "latin-ext";
export type Slabo27pxOptions = GoogleFontOptions<Slabo27pxWeight, Slabo27pxStyle, Slabo27pxSubset>;

/**
 * Slabo 27px — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Slabo27px extends GoogleFont<Slabo27pxWeight, Slabo27pxStyle, Slabo27pxSubset> {
  constructor(options?: Slabo27pxOptions) {
    super(FAMILY, FACES, options);
  }
}
