// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Sofia Sans Extra Condensed";

const FACES = {
  cyrillic: {
    "100-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkh8lxek.woff2",
    "100-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSqJk5kkw.woff2",
    "200-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkh8lxek.woff2",
    "200-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSqJk5kkw.woff2",
    "300-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkh8lxek.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSqJk5kkw.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkh8lxek.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSqJk5kkw.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkh8lxek.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSqJk5kkw.woff2",
    "600-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkh8lxek.woff2",
    "600-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSqJk5kkw.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkh8lxek.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSqJk5kkw.woff2",
    "800-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkh8lxek.woff2",
    "800-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSqJk5kkw.woff2",
    "900-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkh8lxek.woff2",
    "900-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSqJk5kkw.woff2",
  },
  "cyrillic-ext": {
    "100-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkF8lxek.woff2",
    "100-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSjJk5kkw.woff2",
    "200-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkF8lxek.woff2",
    "200-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSjJk5kkw.woff2",
    "300-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkF8lxek.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSjJk5kkw.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkF8lxek.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSjJk5kkw.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkF8lxek.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSjJk5kkw.woff2",
    "600-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkF8lxek.woff2",
    "600-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSjJk5kkw.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkF8lxek.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSjJk5kkw.woff2",
    "800-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkF8lxek.woff2",
    "800-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSjJk5kkw.woff2",
    "900-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkF8lxek.woff2",
    "900-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSjJk5kkw.woff2",
  },
  greek: {
    "100-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFk98lxek.woff2",
    "100-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fStJk5kkw.woff2",
    "200-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFk98lxek.woff2",
    "200-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fStJk5kkw.woff2",
    "300-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFk98lxek.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fStJk5kkw.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFk98lxek.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fStJk5kkw.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFk98lxek.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fStJk5kkw.woff2",
    "600-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFk98lxek.woff2",
    "600-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fStJk5kkw.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFk98lxek.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fStJk5kkw.woff2",
    "800-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFk98lxek.woff2",
    "800-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fStJk5kkw.woff2",
    "900-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFk98lxek.woff2",
    "900-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fStJk5kkw.woff2",
  },
  latin: {
    "100-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkx8lw.woff2",
    "100-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSuJk4.woff2",
    "200-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkx8lw.woff2",
    "200-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSuJk4.woff2",
    "300-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkx8lw.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSuJk4.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkx8lw.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSuJk4.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkx8lw.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSuJk4.woff2",
    "600-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkx8lw.woff2",
    "600-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSuJk4.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkx8lw.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSuJk4.woff2",
    "800-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkx8lw.woff2",
    "800-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSuJk4.woff2",
    "900-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkx8lw.woff2",
    "900-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSuJk4.woff2",
  },
  "latin-ext": {
    "100-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkJ8lxek.woff2",
    "100-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSgJk5kkw.woff2",
    "200-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkJ8lxek.woff2",
    "200-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSgJk5kkw.woff2",
    "300-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkJ8lxek.woff2",
    "300-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSgJk5kkw.woff2",
    "400-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkJ8lxek.woff2",
    "400-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSgJk5kkw.woff2",
    "500-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkJ8lxek.woff2",
    "500-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSgJk5kkw.woff2",
    "600-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkJ8lxek.woff2",
    "600-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSgJk5kkw.woff2",
    "700-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkJ8lxek.woff2",
    "700-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSgJk5kkw.woff2",
    "800-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkJ8lxek.woff2",
    "800-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSgJk5kkw.woff2",
    "900-italic":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxqHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSrFkJ8lxek.woff2",
    "900-normal":
      "https://fonts.gstatic.com/s/sofiasansextracondensed/v6/raxoHjafvdAIOju4GcIfJH0i7zi50X3zRtuLNiMS0fSgJk5kkw.woff2",
  },
} as const;

export type SofiaSansExtraCondensedWeight =
  | "100"
  | "200"
  | "300"
  | "400"
  | "500"
  | "600"
  | "700"
  | "800"
  | "900";
export type SofiaSansExtraCondensedStyle = "italic" | "normal";
export type SofiaSansExtraCondensedSubset =
  | "cyrillic"
  | "cyrillic-ext"
  | "greek"
  | "latin"
  | "latin-ext";
export type SofiaSansExtraCondensedOptions = GoogleFontOptions<
  SofiaSansExtraCondensedWeight,
  SofiaSansExtraCondensedStyle,
  SofiaSansExtraCondensedSubset
>;

/**
 * Sofia Sans Extra Condensed — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class SofiaSansExtraCondensed extends GoogleFont<
  SofiaSansExtraCondensedWeight,
  SofiaSansExtraCondensedStyle,
  SofiaSansExtraCondensedSubset
> {
  constructor(options?: SofiaSansExtraCondensedOptions) {
    super(FAMILY, FACES, options);
  }
}
