// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Space Grotesk";

const FACES = {
  "latin": {
    "300-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPbF4Cw.woff2",
    "400-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPbF4Cw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPbF4Cw.woff2",
    "600-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPbF4Cw.woff2",
    "700-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPbF4Cw.woff2",
  },
  "latin-ext": {
    "300-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPb94C-s0.woff2",
    "400-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPb94C-s0.woff2",
    "500-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPb94C-s0.woff2",
    "600-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPb94C-s0.woff2",
    "700-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPb94C-s0.woff2",
  },
  "vietnamese": {
    "300-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPb54C-s0.woff2",
    "400-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPb54C-s0.woff2",
    "500-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPb54C-s0.woff2",
    "600-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPb54C-s0.woff2",
    "700-normal": "https://fonts.gstatic.com/s/spacegrotesk/v22/V8mDoQDjQSkFtoMM3T6r8E7mPb54C-s0.woff2",
  },
} as const;

export type SpaceGroteskWeight = "300" | "400" | "500" | "600" | "700";
export type SpaceGroteskStyle = "normal";
export type SpaceGroteskSubset = "latin" | "latin-ext" | "vietnamese";
export type SpaceGroteskOptions = GoogleFontOptions<SpaceGroteskWeight, SpaceGroteskStyle, SpaceGroteskSubset>;

/**
 * Space Grotesk — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class SpaceGrotesk extends GoogleFont<SpaceGroteskWeight, SpaceGroteskStyle, SpaceGroteskSubset> {
  constructor(options?: SpaceGroteskOptions) {
    super(FAMILY, FACES, options);
  }
}
