// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Special Gothic Expanded One";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/specialgothicexpandedone/v2/IurO6Zxk74-YaYk1r3HOet4g75ENmBxUmOK61tA0Iu5QmJF_.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/specialgothicexpandedone/v2/IurO6Zxk74-YaYk1r3HOet4g75ENmBxUmOK61tA0Iu5QlpF_GhU.woff2",
  },
} as const;

export type SpecialGothicExpandedOneWeight = "400";
export type SpecialGothicExpandedOneStyle = "normal";
export type SpecialGothicExpandedOneSubset = "latin" | "latin-ext";
export type SpecialGothicExpandedOneOptions = GoogleFontOptions<SpecialGothicExpandedOneWeight, SpecialGothicExpandedOneStyle, SpecialGothicExpandedOneSubset>;

/**
 * Special Gothic Expanded One — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class SpecialGothicExpandedOne extends GoogleFont<SpecialGothicExpandedOneWeight, SpecialGothicExpandedOneStyle, SpecialGothicExpandedOneSubset> {
  constructor(options?: SpecialGothicExpandedOneOptions) {
    super(FAMILY, FACES, options);
  }
}
