// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Stalemate";

const FACES = {
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/stalemate/v24/taiIGmZ_EJq97-UfkZRZva6t.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/stalemate/v24/taiIGmZ_EJq97-UfkZRZs66twZQ.woff2",
  },
} as const;

export type StalemateWeight = "400";
export type StalemateStyle = "normal";
export type StalemateSubset = "latin" | "latin-ext";
export type StalemateOptions = GoogleFontOptions<StalemateWeight, StalemateStyle, StalemateSubset>;

/**
 * Stalemate — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Stalemate extends GoogleFont<
  StalemateWeight,
  StalemateStyle,
  StalemateSubset
> {
  constructor(options?: StalemateOptions) {
    super(FAMILY, FACES, options);
  }
}
