// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Sumana";

const FACES = {
  devanagari: {
    "400-normal": "https://fonts.gstatic.com/s/sumana/v12/4UaDrE5TqRBjGj-29hLj36w.woff2",
    "700-normal": "https://fonts.gstatic.com/s/sumana/v12/4UaArE5TqRBjGj--TDf24Y3M2po.woff2",
  },
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/sumana/v12/4UaDrE5TqRBjGj-29xLj.woff2",
    "700-normal": "https://fonts.gstatic.com/s/sumana/v12/4UaArE5TqRBjGj--TDf24I3M.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/sumana/v12/4UaDrE5TqRBjGj-2-RLj36w.woff2",
    "700-normal": "https://fonts.gstatic.com/s/sumana/v12/4UaArE5TqRBjGj--TDf27o3M2po.woff2",
  },
} as const;

export type SumanaWeight = "400" | "700";
export type SumanaStyle = "normal";
export type SumanaSubset = "devanagari" | "latin" | "latin-ext";
export type SumanaOptions = GoogleFontOptions<SumanaWeight, SumanaStyle, SumanaSubset>;

/**
 * Sumana — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Sumana extends GoogleFont<SumanaWeight, SumanaStyle, SumanaSubset> {
  constructor(options?: SumanaOptions) {
    super(FAMILY, FACES, options);
  }
}
