// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Texturina";

const FACES = {
  "latin": {
    "100-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYcagf.woff2",
    "100-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQRocw.woff2",
    "200-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYcagf.woff2",
    "200-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQRocw.woff2",
    "300-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYcagf.woff2",
    "300-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQRocw.woff2",
    "400-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYcagf.woff2",
    "400-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQRocw.woff2",
    "500-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYcagf.woff2",
    "500-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQRocw.woff2",
    "600-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYcagf.woff2",
    "600-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQRocw.woff2",
    "700-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYcagf.woff2",
    "700-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQRocw.woff2",
    "800-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYcagf.woff2",
    "800-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQRocw.woff2",
    "900-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYcagf.woff2",
    "900-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQRocw.woff2",
  },
  "latin-ext": {
    "100-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYf6gfBlw.woff2",
    "100-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQpoc7Ab.woff2",
    "200-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYf6gfBlw.woff2",
    "200-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQpoc7Ab.woff2",
    "300-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYf6gfBlw.woff2",
    "300-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQpoc7Ab.woff2",
    "400-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYf6gfBlw.woff2",
    "400-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQpoc7Ab.woff2",
    "500-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYf6gfBlw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQpoc7Ab.woff2",
    "600-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYf6gfBlw.woff2",
    "600-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQpoc7Ab.woff2",
    "700-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYf6gfBlw.woff2",
    "700-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQpoc7Ab.woff2",
    "800-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYf6gfBlw.woff2",
    "800-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQpoc7Ab.woff2",
    "900-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYf6gfBlw.woff2",
    "900-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQpoc7Ab.woff2",
  },
  "vietnamese": {
    "100-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYfqgfBlw.woff2",
    "100-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQtoc7Ab.woff2",
    "200-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYfqgfBlw.woff2",
    "200-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQtoc7Ab.woff2",
    "300-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYfqgfBlw.woff2",
    "300-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQtoc7Ab.woff2",
    "400-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYfqgfBlw.woff2",
    "400-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQtoc7Ab.woff2",
    "500-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYfqgfBlw.woff2",
    "500-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQtoc7Ab.woff2",
    "600-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYfqgfBlw.woff2",
    "600-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQtoc7Ab.woff2",
    "700-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYfqgfBlw.woff2",
    "700-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQtoc7Ab.woff2",
    "800-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYfqgfBlw.woff2",
    "800-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQtoc7Ab.woff2",
    "900-italic": "https://fonts.gstatic.com/s/texturina/v32/c4mz1nxpEtL3pXiAulR5mL129FhZmLj7I4oiSUJYfqgfBlw.woff2",
    "900-normal": "https://fonts.gstatic.com/s/texturina/v32/c4mx1nxpEtL3pXiAulRTkY-HGmNEX1b9NspjGQtoc7Ab.woff2",
  },
} as const;

export type TexturinaWeight = "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900";
export type TexturinaStyle = "italic" | "normal";
export type TexturinaSubset = "latin" | "latin-ext" | "vietnamese";
export type TexturinaOptions = GoogleFontOptions<TexturinaWeight, TexturinaStyle, TexturinaSubset>;

/**
 * Texturina — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Texturina extends GoogleFont<TexturinaWeight, TexturinaStyle, TexturinaSubset> {
  constructor(options?: TexturinaOptions) {
    super(FAMILY, FACES, options);
  }
}
