// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Tilt Neon";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/tiltneon/v12/E21L_d7gguXdwD9LEFY2WCeElCNtd-eBqpHp1TzrkJSmwpj5ndxquUK6UOc.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/tiltneon/v12/E21L_d7gguXdwD9LEFY2WCeElCNtd-eBqpHp1TzrkJSmwpj5ndxquUK0UOeVJw.woff2",
  },
  "vietnamese": {
    "400-normal": "https://fonts.gstatic.com/s/tiltneon/v12/E21L_d7gguXdwD9LEFY2WCeElCNtd-eBqpHp1TzrkJSmwpj5ndxquUK1UOeVJw.woff2",
  },
} as const;

export type TiltNeonWeight = "400";
export type TiltNeonStyle = "normal";
export type TiltNeonSubset = "latin" | "latin-ext" | "vietnamese";
export type TiltNeonOptions = GoogleFontOptions<TiltNeonWeight, TiltNeonStyle, TiltNeonSubset>;

/**
 * Tilt Neon — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class TiltNeon extends GoogleFont<TiltNeonWeight, TiltNeonStyle, TiltNeonSubset> {
  constructor(options?: TiltNeonOptions) {
    super(FAMILY, FACES, options);
  }
}
