// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Timmana";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/timmana/v14/6xKvdShfL9yK-rvpOmzRKQ.woff2",
  },
  "telugu": {
    "400-normal": "https://fonts.gstatic.com/s/timmana/v14/6xKvdShfL9yK-rvpOnDRKUwJ.woff2",
  },
} as const;

export type TimmanaWeight = "400";
export type TimmanaStyle = "normal";
export type TimmanaSubset = "latin" | "telugu";
export type TimmanaOptions = GoogleFontOptions<TimmanaWeight, TimmanaStyle, TimmanaSubset>;

/**
 * Timmana — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Timmana extends GoogleFont<TimmanaWeight, TimmanaStyle, TimmanaSubset> {
  constructor(options?: TimmanaOptions) {
    super(FAMILY, FACES, options);
  }
}
