// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Tinos";

const FACES = {
  "cyrillic": {
    "400-italic": "https://fonts.gstatic.com/s/tinos/v26/buE2poGnedXvwjX-TmJJ9RI-.woff2",
    "400-normal": "https://fonts.gstatic.com/s/tinos/v26/buE4poGnedXvwjX_fmRR8Q.woff2",
    "700-italic": "https://fonts.gstatic.com/s/tinos/v26/buEzpoGnedXvwjX-Rt1s4Ckf_exL.woff2",
    "700-normal": "https://fonts.gstatic.com/s/tinos/v26/buE1poGnedXvwj1AW3Fq0C8H-Q.woff2",
  },
  "cyrillic-ext": {
    "400-italic": "https://fonts.gstatic.com/s/tinos/v26/buE2poGnedXvwjX-TmtJ9RI-.woff2",
    "400-normal": "https://fonts.gstatic.com/s/tinos/v26/buE4poGnedXvwjX2fmRR8Q.woff2",
    "700-italic": "https://fonts.gstatic.com/s/tinos/v26/buEzpoGnedXvwjX-Rt1s4CAf_exL.woff2",
    "700-normal": "https://fonts.gstatic.com/s/tinos/v26/buE1poGnedXvwj1AW3Fj0C8H-Q.woff2",
  },
  "greek": {
    "400-italic": "https://fonts.gstatic.com/s/tinos/v26/buE2poGnedXvwjX-TmVJ9RI-.woff2",
    "400-normal": "https://fonts.gstatic.com/s/tinos/v26/buE4poGnedXvwjX4fmRR8Q.woff2",
    "700-italic": "https://fonts.gstatic.com/s/tinos/v26/buEzpoGnedXvwjX-Rt1s4C4f_exL.woff2",
    "700-normal": "https://fonts.gstatic.com/s/tinos/v26/buE1poGnedXvwj1AW3Ft0C8H-Q.woff2",
  },
  "greek-ext": {
    "400-italic": "https://fonts.gstatic.com/s/tinos/v26/buE2poGnedXvwjX-TmpJ9RI-.woff2",
    "400-normal": "https://fonts.gstatic.com/s/tinos/v26/buE4poGnedXvwjX3fmRR8Q.woff2",
    "700-italic": "https://fonts.gstatic.com/s/tinos/v26/buEzpoGnedXvwjX-Rt1s4CEf_exL.woff2",
    "700-normal": "https://fonts.gstatic.com/s/tinos/v26/buE1poGnedXvwj1AW3Fi0C8H-Q.woff2",
  },
  "hebrew": {
    "400-italic": "https://fonts.gstatic.com/s/tinos/v26/buE2poGnedXvwjX-TmRJ9RI-.woff2",
    "400-normal": "https://fonts.gstatic.com/s/tinos/v26/buE4poGnedXvwjX5fmRR8Q.woff2",
    "700-italic": "https://fonts.gstatic.com/s/tinos/v26/buEzpoGnedXvwjX-Rt1s4C8f_exL.woff2",
    "700-normal": "https://fonts.gstatic.com/s/tinos/v26/buE1poGnedXvwj1AW3Fs0C8H-Q.woff2",
  },
  "latin": {
    "400-italic": "https://fonts.gstatic.com/s/tinos/v26/buE2poGnedXvwjX-TmZJ9Q.woff2",
    "400-normal": "https://fonts.gstatic.com/s/tinos/v26/buE4poGnedXvwjX7fmQ.woff2",
    "700-italic": "https://fonts.gstatic.com/s/tinos/v26/buEzpoGnedXvwjX-Rt1s4C0f_Q.woff2",
    "700-normal": "https://fonts.gstatic.com/s/tinos/v26/buE1poGnedXvwj1AW3Fu0C8.woff2",
  },
  "latin-ext": {
    "400-italic": "https://fonts.gstatic.com/s/tinos/v26/buE2poGnedXvwjX-TmhJ9RI-.woff2",
    "400-normal": "https://fonts.gstatic.com/s/tinos/v26/buE4poGnedXvwjX1fmRR8Q.woff2",
    "700-italic": "https://fonts.gstatic.com/s/tinos/v26/buEzpoGnedXvwjX-Rt1s4CMf_exL.woff2",
    "700-normal": "https://fonts.gstatic.com/s/tinos/v26/buE1poGnedXvwj1AW3Fg0C8H-Q.woff2",
  },
  "vietnamese": {
    "400-italic": "https://fonts.gstatic.com/s/tinos/v26/buE2poGnedXvwjX-TmlJ9RI-.woff2",
    "400-normal": "https://fonts.gstatic.com/s/tinos/v26/buE4poGnedXvwjX0fmRR8Q.woff2",
    "700-italic": "https://fonts.gstatic.com/s/tinos/v26/buEzpoGnedXvwjX-Rt1s4CIf_exL.woff2",
    "700-normal": "https://fonts.gstatic.com/s/tinos/v26/buE1poGnedXvwj1AW3Fh0C8H-Q.woff2",
  },
} as const;

export type TinosWeight = "400" | "700";
export type TinosStyle = "italic" | "normal";
export type TinosSubset = "cyrillic" | "cyrillic-ext" | "greek" | "greek-ext" | "hebrew" | "latin" | "latin-ext" | "vietnamese";
export type TinosOptions = GoogleFontOptions<TinosWeight, TinosStyle, TinosSubset>;

/**
 * Tinos — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Tinos extends GoogleFont<TinosWeight, TinosStyle, TinosSubset> {
  constructor(options?: TinosOptions) {
    super(FAMILY, FACES, options);
  }
}
