// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Vidaloka";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/vidaloka/v19/7cHrv4c3ipenMKlEavs7wH8.woff2",
  },
} as const;

export type VidalokaWeight = "400";
export type VidalokaStyle = "normal";
export type VidalokaSubset = "latin";
export type VidalokaOptions = GoogleFontOptions<VidalokaWeight, VidalokaStyle, VidalokaSubset>;

/**
 * Vidaloka — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Vidaloka extends GoogleFont<VidalokaWeight, VidalokaStyle, VidalokaSubset> {
  constructor(options?: VidalokaOptions) {
    super(FAMILY, FACES, options);
  }
}
