// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Volkhov";

const FACES = {
  "latin": {
    "400-italic": "https://fonts.gstatic.com/s/volkhov/v18/SlGSmQieoJcKemNecTA0h1R3.woff2",
    "400-normal": "https://fonts.gstatic.com/s/volkhov/v18/SlGQmQieoJcKemNecTUEhQ.woff2",
    "700-italic": "https://fonts.gstatic.com/s/volkhov/v18/SlGXmQieoJcKemNecTA8PHFibxwQ.woff2",
    "700-normal": "https://fonts.gstatic.com/s/volkhov/v18/SlGVmQieoJcKemNeeY4hkHNSbQ.woff2",
  },
} as const;

export type VolkhovWeight = "400" | "700";
export type VolkhovStyle = "italic" | "normal";
export type VolkhovSubset = "latin";
export type VolkhovOptions = GoogleFontOptions<VolkhovWeight, VolkhovStyle, VolkhovSubset>;

/**
 * Volkhov — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class Volkhov extends GoogleFont<VolkhovWeight, VolkhovStyle, VolkhovSubset> {
  constructor(options?: VolkhovOptions) {
    super(FAMILY, FACES, options);
  }
}
