// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Waiting for the Sunrise";

const FACES = {
  latin: {
    "400-normal":
      "https://fonts.gstatic.com/s/waitingforthesunrise/v23/WBL1rFvOYl9CEv2i1mO6KUW8RKWJ2zoXoz5JsbZX_B4.woff2",
  },
  "latin-ext": {
    "400-normal":
      "https://fonts.gstatic.com/s/waitingforthesunrise/v23/WBL1rFvOYl9CEv2i1mO6KUW8RKWJ2zoXoz5JsbZZ_B7pYg.woff2",
  },
} as const;

export type WaitingForTheSunriseWeight = "400";
export type WaitingForTheSunriseStyle = "normal";
export type WaitingForTheSunriseSubset = "latin" | "latin-ext";
export type WaitingForTheSunriseOptions = GoogleFontOptions<
  WaitingForTheSunriseWeight,
  WaitingForTheSunriseStyle,
  WaitingForTheSunriseSubset
>;

/**
 * Waiting for the Sunrise — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class WaitingForTheSunrise extends GoogleFont<
  WaitingForTheSunriseWeight,
  WaitingForTheSunriseStyle,
  WaitingForTheSunriseSubset
> {
  constructor(options?: WaitingForTheSunriseOptions) {
    super(FAMILY, FACES, options);
  }
}
