// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "ZCOOL QingKe HuangYou";

const FACES = {
  "latin": {
    "400-normal": "https://fonts.gstatic.com/s/zcoolqingkehuangyou/v16/2Eb5L_R5IXJEWhD3AOhSvFC554MOOahI4mR4jPe9.woff2",
  },
} as const;

export type ZCOOLQingKeHuangYouWeight = "400";
export type ZCOOLQingKeHuangYouStyle = "normal";
export type ZCOOLQingKeHuangYouSubset = "latin";
export type ZCOOLQingKeHuangYouOptions = GoogleFontOptions<ZCOOLQingKeHuangYouWeight, ZCOOLQingKeHuangYouStyle, ZCOOLQingKeHuangYouSubset>;

/**
 * ZCOOL QingKe HuangYou — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class ZCOOLQingKeHuangYou extends GoogleFont<ZCOOLQingKeHuangYouWeight, ZCOOLQingKeHuangYouStyle, ZCOOLQingKeHuangYouSubset> {
  constructor(options?: ZCOOLQingKeHuangYouOptions) {
    super(FAMILY, FACES, options);
  }
}
