// AUTO-GENERATED by scripts/generate.ts — do not edit.
import { GoogleFont, type GoogleFontOptions } from "../runtime.js";

const FAMILY = "Zen Antique";

const FACES = {
  cyrillic: {
    "400-normal": "https://fonts.gstatic.com/s/zenantique/v14/AYCPpXPnd91Ma_Zf-Ri2JUJp5vO_5Q.woff2",
  },
  greek: {
    "400-normal": "https://fonts.gstatic.com/s/zenantique/v14/AYCPpXPnd91Ma_Zf-Ri2JUJu5vO_5Q.woff2",
  },
  latin: {
    "400-normal": "https://fonts.gstatic.com/s/zenantique/v14/AYCPpXPnd91Ma_Zf-Ri2JUJt5vM.woff2",
  },
  "latin-ext": {
    "400-normal": "https://fonts.gstatic.com/s/zenantique/v14/AYCPpXPnd91Ma_Zf-Ri2JUJj5vO_5Q.woff2",
  },
} as const;

export type ZenAntiqueWeight = "400";
export type ZenAntiqueStyle = "normal";
export type ZenAntiqueSubset = "cyrillic" | "greek" | "latin" | "latin-ext";
export type ZenAntiqueOptions = GoogleFontOptions<
  ZenAntiqueWeight,
  ZenAntiqueStyle,
  ZenAntiqueSubset
>;

/**
 * Zen Antique — Google font. Pass `weights`/`styles` to register a subset of
 * faces (omit for all) and `subset` to choose the character set (default "latin").
 */
export default class ZenAntique extends GoogleFont<
  ZenAntiqueWeight,
  ZenAntiqueStyle,
  ZenAntiqueSubset
> {
  constructor(options?: ZenAntiqueOptions) {
    super(FAMILY, FACES, options);
  }
}
