packages:
  - "packages/*"
  - "demo"

onlyBuiltDependencies:
  - skia-canvas
  - esbuild
  - "@ffmpeg-installer/ffmpeg"
  - "@ffmpeg-installer/darwin-arm64"
  - "@ffmpeg-installer/darwin-x64"
  - "@ffmpeg-installer/linux-x64"
  - "@ffmpeg-installer/linux-arm64"
  - "@ffmpeg-installer/win32-x64"
